### ISSUE TITLE
Order/Create Request

### ISSUE THREAD

**Issue by chhinendu** [service-portal/documentation#100]
Can anyone please explain how "$http.post(spUtil.getURL('sc_cat_item'), $sp.getCatalogItem(sys_id))", this single post method creates a request for us ? Just trying to understand the request creation process.

**Comment by patrickw14** [comment]
Basically, when you do a one-click order on a catalog item, we create a new cart, add the catalog item to that cart, trigger a checkout, then delete the cart again. It's a little bit magic, but most of the logic is contained by a couple of Script Includes, primarily SPCatalogOrder.
