### ISSUE TITLE
Setting a site theme at run time?

### ISSUE THREAD

**Issue by jfbenedict** [service-portal/documentation#101]
Just curious if there is any API support for setting the site theme at run-time?  Looking for an MSP type of solution where we have one site but based off of the logged user we would use one theme vs another.  If a solution does not exist, do you think a solution where we redirect the user to their specific site is best solution to this challenge?

**Comment by patrickw14** [comment]
I would suggest you dynamically direct users to different portals, which each define their own themes. We don't have any support today for dynamically choosing themes at runtime.
