### ISSUE TITLE
SP Model

### ISSUE THREAD

**Issue by klima** [service-portal/documentation#102]
Where i can edit layout of sp-model?

`<sp-model form-model="item" mandatory="allMandatory[item.sys_id]"></sp-model>`

**Comment by CapaJC** [comment]
That file's currently in the filesystem and not in the database. I don't know if there's an easy way to view hardcoded XML files like that.

More specifically, that sp-model directive is defined by the directive.spModel.js file which specifies as its template the sp_model.xml file I mentioned.

**Comment by patrickw14** [comment]
Changing the layout of sp-model isn't support at this time, unfortunately. No easy way to accomplish this today. The most you can do is design a new form in the platform UI, ascribe it to a view, and reference that view in your forms, which is absolutely supported.
