### ISSUE TITLE
$sp.logStat help

### ISSUE THREAD

**Issue by zzjasonzz** [service-portal/documentation#103]
Can you give us some quick documentation on $sp.logStat?  We like the data that is being logged into sp_log and want to add a few more types of log entries into it.  If there is a way to see the code behind that method that would help too.

**Comment by patrickw14** [comment]
There really isn't much to it, but I wrote a new entry for it here: https://github.com/service-portal/documentation/blob/master/documentation/widget_server_script_apis.md

There isn't too much to the method either, it's really just grabbing the values that you pass into your call to $sp.logStat and sticking them in a new sp_log record. Hopefully that's helpful!
