### ISSUE TITLE
Problem with public/not public pages and SSO

### ISSUE THREAD

**Issue by goranlundqvist** [service-portal/documentation#107]
Hi,

I have a problem that I thought others would have, but it doesn't seems so. We have a public first page. And then some of the widgets there points to pages that aint public. My problem is that I can't get the Service Portal to redirect to our SSO if not the whole portal requires login.

Pretty much the scenario. First page(index) is public, but when they for example click on "get help" which points to a record producer they should get the SSO login.  
If I put false on $SP at the sys_public also the first page gets redirected to login, to SSO thou, but first page shouldnt :(  
If I put true on $SP the first page get reachable without login. and if I have a login page the "order now" goes to that one instead of the SSO login.  
If I remove login page on the portal record and press Order now it goes to the page but it's blank. I guess since I aint logged in and ACL stops from getting any info.  I guess that the reason that adding like sc_category to sys_public is since the URL is still sp and ID pointing to the sc_category (.service-now.com/sp?id=sc_category&sys_id)

atm. I have solved this put putting a login page and then put a public html widget which redirects to the correct login. Like this:

function() { /* widget controller */ var c = this; window.location = "../saml_redirector.do?sysparm_uri=/sp"; }

I think this is kind of a weird to need to use this and hoping that someone here knows a better way.

//Göran

**Comment by patrickw14** [comment]
Could you check to make sure that this property is enabled: glide.authenticate.multisso.enabled
And check that this property is pointing to your IDP? glide.authenticate.sso.redirect.idp

If both of those properties are set, any instance of the login widget that appears on a page should automatically redirect users to the IDP specified by glide.authenticate.sso.redirect.idp

**Comment by goranlundqvist** [comment]
We don't have those properties. Some background. These instances isn't fresh helsinki, but come from Eureka and forward. I noticed that when I went to SAML settings, it asked me to upgrade to the latest SAML plugin. And this is the one which has the properties you are asking for. I'll check that out and come back when I got some results.

**Comment by goranlundqvist** [comment]
Well.. Almost there.. I activated the plugin, put the login widget the login page and it started to work. The "none" public page redirected to the login page, which then saw the login widget and send me to the SSO.

The "minor" problem is... I can't login with SSO, now it says "User xxxx not found" and I get logged out. So I guess by activating the plugin, something got messed up. Any idea?

**Comment by goranlundqvist** [comment]
got it =) the migratated data in SAML changed the IDP date on the user field from user_name to email by some strange thing.. put user_name there and it works =)

**Comment by patrickw14** [comment]
Woohoo! Glad you got it going!
