### ISSUE TITLE
Simple List - View management & Max. Entries

### ISSUE THREAD

**Issue by schusterf** [service-portal/documentation#108]
Hello,

Just recently stumbled upon the fact, that Simple List doesn't pass on the view to the "list" page, which includes the Data Table from URL definition widget.

Use Case: 
- Create a new Simple List widget instance, do some minimal configuration (define a table e.g. Incident, display field, link to **form** - finally set a view, e.g. **Self-Service**).
- Go to the page that contains that widget 
- Click on one of the first 5 records of the widget, you'll notice the view is passed on to the form correctly
- Click on **View All**, you'll see that the view is not passed on within the URL and therefore also not passed onto the actual form when a user clicks on a record from the Data Table from URL definition widget/list.

That can easily be fixed by changing the view logic in the Server Script as well as passing on the view in the Client Controller (see attached screenshot).
![simplelistwithview](https://cloud.githubusercontent.com/assets/18425162/18517311/14586ad6-7a59-11e6-9fd5-1c010a549d9f.png)

Another very helpful addition would be to have the Max. Entries exposed in the Widget Options, so we don't have to go to the Platform View to change those.

**Comment by patrickw14** [comment]
We'll look into this issue - thanks Frank!

**Comment by CapaJC** [comment]
PRB709643
