### ISSUE TITLE
How to use a custom widget for a catalog variable?

### ISSUE THREAD

**Issue by zzjasonzz** [service-portal/documentation#111]
Is there any documentation on how to use a custom widget attached to a Service Catalog Item variable?  We see there's a Widget field for UI Macro's available but is there any documentation or examples of this being used?  I can't find any in our instances running Helsinki Patch 4.

![image](https://cloud.githubusercontent.com/assets/20165428/18672827/9ffec8a6-7f17-11e6-977f-9e464834c6d1.png)

**Comment by CapaJC** [comment]
If you have a Macro variable, and if that variable has a Widget reference, the referenced Widget will be placed on the page in that location on the Catalog Item.

I don't think we ship any of those by default, but it's something we provide for in lieu of supporting UI Macros.

**Comment by CapaJC** [comment]
Only doc I see is here (look for the word "Macro": https://github.com/service-portal/documentation/blob/fb562cd28ee56cfaa095e0d9aae2c247ee961ad3/documentation/client_scripting.md

**Comment by zzjasonzz** [comment]
Thanks, that should be good enough to get us started.
