### ISSUE TITLE
Unable to determine Mobile App vs. Browser when accessing Catalog Items from within Service Portal

### ISSUE THREAD

**Issue by danielpaff** [service-portal/documentation#112]
I have a customer that would like to set the "Contact Type" to "App" when an Incident is created from the Mobile App.  We have this working well, with one exception.  If the user access the "Create Incident" Catalog Item from within the Service Portal->Get Help->Create Incident it is set to "App" regardless of how they are accessing it (Desktop Browser, Mobile Browser, Mobile App) as I can't seem to make the distinction within Service Portal of how it is being accessed.  I've tried a couple of different things, but what I have right now is a Client Script:

function onLoad() {
	if(window === null){
		g_form.setValue('contact_type', 'app');
		alert('We don\'t have a window');
		alert(window);
	} else {
		g_form.setValue('contact_type', 'self-service');
		alert('we do have a window');
	}
}

The Contact Type is set to "App" and alerts are generated saying, "We don't have a window" and "null" when the Item loads via Service Portal even when access from a Desktop Browser.

I've thought about using gs.isMobile() in a Business Rule, but I understand that is currently not working.

I'm not sure the "window" approach is valid, either, as I think this [page](https://github.com/service-portal/documentation/blob/master/documentation/client_scripting.md#checking-desktop-vs-mobile-runtime) - contradicts itself.

Any guidance would be appreciated.  I've been told this isn't a show stopper, but they would really like to have this information available to them.

Thanks,

Dan

**Comment by wlisac** [comment]
@danielpaff Mobile and ServicePortal share the same Client Script environment where `window` access is disabled.

This is why `window === null` is always `true` in ServicePortal regardless of the device type that is being used.

**Comment by danielpaff** [comment]
@wlisac Thanks for the feedback. That's what I expected given the documentation.  Having said that, is there any way to tell how the ServicePortal is being accessed (Desktop browser vs. Mobile browser vs. Mobile App)? I'm pretty doubtful...

**Comment by patrickw14** [comment]
Starting in Helsinki Patch 5 and Istanbul, you can actually check for the presence of a global variable called NOW.sp in your client scripts. So, in your scripts, you can do something like this:

`
if (!window && NOW.sp) {
  //do your service portal stuff
} else if (!window) {
  //do your mobile stuff
} else {
  //do your desktop stuff
}
`

That oughta work 😄

**Comment by danielpaff** [comment]
@patrickw14 Thanks for the feedback, however it still seems you won't be able to tell how ServicePortal is being accessed (App vs. some other mechanism).  Is that correct?

The issue is if a user accesses ServicePortal using the iPhone/Android App and navigates to the "Create Incident" Catalog Item, they would like to know that the user was using the App.  I don't think that is possible.  If not, I just need to give them that feedback and move on...

**Comment by patrickw14** [comment]
Unfortunately at this point in time, there is no way to check if you are in a SP versus a Mobile scripting environment. Apologies!
