### ISSUE TITLE
How do I add Search to Header?

### ISSUE THREAD

**Issue by aryandelhi** [service-portal/documentation#114]
Is there any way to include search to serviceportal header?

**Comment by NicholasHord** [comment]
Following

**Comment by davidmckenzie** [comment]
Pretty simple - clone the stock header and add in something like the following:

In the HTML template after: `<ul ng-if="::user.logged_in" class="nav navbar-nav">`
Add:
`<li><span class="navbar-search"><sp-widget widget="data.typeahead"></sp-widget></span></li>`

In the CSS add:

`.navbar-search {
  margin-top: 17px;
  top: 50%;
  display: block;
  height: 50px;
  padding: 0;
  max-height: 50px;
  max-width: 300px;
  position: relative;
}`

And in server script add:

`data.typeahead = $sp.getWidgetFromInstance('typeahead-search');`

YMMV :)

I ran into some issues with the size of the search bar, specifically on mobile devices, but it works, probably needs some CSS tweaking.

**Comment by patrickw14** [comment]
Issue seems resolved - feel free to reopen if not
