### ISSUE TITLE
Variable summarizer not honoring "Visible on Summaries"

### ISSUE THREAD

**Issue by NYancer3** [service-portal/documentation#115]
When looking at the approval record in "My Approvals," the variable summary is showing items that are set to "Visible on Summaries = false." Looking at the Approvals widgets, it looks like the function $sp.getRecordVariablesArray is not filtering these out. It also looks like it is not returning "Visible on Summaries" as an attribute that we could use in our own widget to stop displaying these.

Any idea how we can clean up the summaries to not show variables we want hidden?

**Comment by CapaJC** [comment]
No idea w/ current code, but perhaps someone else will chime in w/ an idea.

I'll open a Problem for this. I suspect "summaries" refers to the normal UI's approval summarizer, but we'll confirm and enhance the Service Portal code if practical.

**Comment by CapaJC** [comment]
If you'll open an Incident, that'll help us with justification for the eventual code change. Otherwise there are extra extra hoops through jumping must occur.

**Comment by CapaJC** [comment]
You can reference PRB714564, which I just created

**Comment by NYancer3** [comment]
Will do, thank you :)

**Comment by patrickw14** [comment]
Closed - PRB has been created.

**Comment by bernie-d** [comment]
getRecordVariablesArray()

This is not returning the value for visible_summary. It should be edited to return it. This also stops the widgets for the approval record from working correctly as they are filtered by this value being true
