### ISSUE TITLE
Attachment Upload progress bar

### ISSUE THREAD

**Issue by t1mb0b** [service-portal/documentation#116]
Any way to implement a progress bar in SP for uploading attachments? We just rolled out SP this weekend, and some feedback we have is if a user chooses a larger file (i.e 10M+), there is no indication anything is happening once they select the attachment. The attachment eventually appears on the form, but there is no indication anything is happening in the background until then. 

Looks 'sp-attachment-manager' is the template called in the form widget. Any way to access this to modify?

I suppose this is more of an enhancement request than it would be an issue.

Cheers,

Tim

**Comment by schusterf** [comment]
If you upload something, that will trigger the OOTB Loading Spinner, which is represented by the 3 little dots in the header menu. These are not very obvious, but you could implement your own loading spinner for sure.
![loadingspinner](https://cloud.githubusercontent.com/assets/18425162/19083731/991db4d4-8a20-11e6-9c36-60c1dee748e9.png)

That's the snippet, which is fired when loading starts/stops:
$scope.$on('sp_loading_indicator', function(e, value) {
c.isLoading = value;
});

You could now just go to e.g. [http://loading.io](http://loading.io) and create your own custom spinner, e.g. in the header or on a specific page if you would want to.

I'll plan to write a quick blog tutorial on that in the next week or two.

**Comment by t1mb0b** [comment]
Awesome, thanks Frank!

 Cheers,

Tim

**Comment by NicholasHord** [comment]
Interested in the blog post as well, @schusterf

**Comment by schusterf** [comment]
Travel and workshops got in my way, but I should find some time next week.

**Comment by patrickw14** [comment]
Enhancement requested noted! Cheers 🍻

**Comment by schusterf** [comment]
Well, that took a lot longer than I expected/wanted, but the post is finally online on [Community](https://community.servicenow.com/community/develop/blog/2016/12/28/service-portal-creating-a-custom-loading-spinner). Hope that helps!
