### ISSUE TITLE
spUtil.addInfoMessage and spUtil.addTrivialMessage disappear after a few seconds

### ISSUE THREAD

**Issue by dkearney2** [service-portal/documentation#118]
spUtil.addInfoMessage and spUtil.addTrivialMessage provide messages on the form, however they are disappearing after a few seconds.  Is there a method for making the messages stick?

**Comment by CapaJC** [comment]
A user cannot cancel the 3-second "trivial" message auto-dismissal, but hovering over an "info" or "error" message will make it stick.

Looking at service.spUtil.js and directive.spNotifications.js, it doesn't look like there is currently a message type that will stick regardless of hovering :(

**Comment by patrickw14** [comment]
We will look into possibly introducing sticky notifications in a future release. Thank you!
