### ISSUE TITLE
FullCalendar Dependency is broken

### ISSUE THREAD

**Issue by john-boyland** [service-portal/documentation#122]
In Service Portal under Dependencies -> fullcalendar -> JS Includes -> /scripts/fullcalendar-2.6.1/fullcalendar.js  this link seems to be broken preventing the use of this library.

**Comment by patrickw14** [comment]
Good catch - that dependency definitely shouldn't have made it to the core plugin. We'll remove it.

If you wanted to use the third-party fullcalendar library, you can go ahead and create a new sp_dependency for it
