### ISSUE TITLE
Service Portal Survey Widget?

### ISSUE THREAD

**Issue by zzjasonzz** [service-portal/documentation#124]
Are there any plans to release a Survey Widget for Service Portal?  Currently we are using iframes to display surveys in Service Portal.

**Comment by assertivist** [comment]
👍 I started to port this myself, then realized that there is a `<g2:com.snc.assessment_core_take />` element that there is no source to (maps to a Java class). Someone was able to give me a list of the field types but there's a large amount, and our surveys only use one or two types of questions:

```
yes_no
multi_line_text
multiple_choice
numeric_scale
select_box
single_line_text
check_box
reference
date
date_time
label
break
macro
ui_page
wide_single_line_text
macro_with_abel
lookup_select_box
container_start
container_end
list_collector
lookup_multiple_choice
html
container_split
masked
email
url
```

If you want, I can share what I manage to get together.

**Comment by schusterf** [comment]
A Survey Widget will be released as part of Istanbul. That does not necessarily mean, that you'll have to upgrade to Istanbul since Widgets are mostly self-contained, so you should be able to utilize an Istanbul instance and then leverage the widget code, the Angular providers, possible dependencies etc.

**Comment by assertivist** [comment]
Good news. This was quickly turning into a nightmarish undertaking, even for the two question types we use.

**Comment by patrickw14** [comment]
Closing because issue seems resolved - feel free to reopen if not
