### ISSUE TITLE
SP Modal not working

### ISSUE THREAD

**Issue by mattifh** [service-portal/documentation#127]
I am trying to use the modal which is referenced in here: documentation/documentation/spModal.md and no matter how I am trying to do this, I get this error message. Are there dependencies that need to be loaded or this is a document for unsupported functions?

Error: "Unknown provider: spModalProvider"

**Comment by thijsdaemen** [comment]
We had this issue today, make sure you are on Helsinki patch 5. I think it was added in that patch. That fixed it for us.

**Comment by patrickw14** [comment]
^ Good catch, I just updated the spModal documentation to reflect that.

**Comment by mattifh** [comment]
Thanks thijsdaemen,
you are correct. I've just tested on a patch 5 instance and it works. I don't see any provider for spmodal. Is there a way to pull this for any instance that is not on patch 5? My client can't go to patch 5 for a foreseeable future.

**Comment by patrickw14** [comment]
Maybe you can with a little bit of hacking - service.spModal.js exists on the file system, so it isn't possible to simply port that over. However, you can look at the source code of that service in your Developer console in your favorite browser and turn that into an SP angular provider! Then you can pull that dependency into whatever widgets you'd like. I don't think it would take too long to do.

I haven't tried it myself, but I can't see why that wouldn't work. Good luck!
