### ISSUE TITLE
Pass a sys_id to an embedded widget inside a modal, possible?

### ISSUE THREAD

**Issue by mattifh** [service-portal/documentation#128]
I am working on a solution that opens an embedded widget on a modal and I need to pass the sys_id of the article along with the widget. Is this possible? I've been spending hours with no luck.

Here is my HTML for the modal:
<div ng-repeat="a in data.articles" class="m-b" >
       
        <button ng-click="c.onWidget(a.sys_id)" class="btn btn-default"> {{a.short_description}} </button>

My client Script portion:
function($scope, $uibModal, spUtil) {
	var c = this;
	var instance;  // modal instance

c.onWidget = function(articleID) {
	//data.kbArticleWidget = spUtil.get('kb_article_contextual', {sys_id: articleID});
  instance =  $uibModal.open({
					templateUrl: 'kb_modal_contextual.html',
				// template: spUtil.get('kb_article_contextual', {sys_id: articleID}),
					scope: $scope
        })    
    }
		c.closeModal = function() {
		 instance.dismiss('cancel');
	
	}
}

My Server script:
	data.kbArticleWidget = $sp.getWidget('kb_article_contextual',  null);

I'll appreciate any feedback
Thanks,

**Comment by davidmckenzie** [comment]
Could you use $sp.getParameter("sys_id") to get it from the URL?

**Comment by mattifh** [comment]
I have the sys_id for each item/article. The issue is that I am not sure how to pass it to the embedded widget within the modal.

**Comment by davidmckenzie** [comment]
Yeah you'll want to pass it from the server script rather than the client script. :)

**Comment by mattifh** [comment]
I've made some progress where I can pass the sys_id as an option. Here is how I am testing it with a hard-coded sys_id from the server side for testing only.

`data.kbArticleWidget = $sp.getWidget('kb_article_contextual', options='{"kb_sys_id": "845ee43187032100deddb882a2e3ecda",}');`

My question is now how to do the same on the client side within this script:

`c.onWidget = function(articleID) {
		
	//c.data.kbArticleWidget = spUtil.get('kb_article_contextual', options='{"kb_sys_id": "845ee43187032100deddb882a2e3ecda",}');
  instance =  $uibModal.open({
					templateUrl: 'kb_modal_contextual.html',
				// template: spUtil.get('kb_article_contextual', {sys_id: articleID}),
					scope: $scope
        })    
    }
		c.closeModal = function() {
		 instance.dismiss('cancel');
	
	}`

HTML Code:
` <div ng-repeat="a in data.articles" class="m-b" >
       
        <button ng-click="c.onWidget(a.sys_id)" class="btn btn-default"> {{a.short_description}} </button>`

**Comment by nathkelly** [comment]
I had a list view for delegations where users clicked "Edit" on a list item and needed that to load the info for the delegate into the modal. The way I achieved that was when the user clicked edit it would run the following:

`	c.editDelegate = function(del_id) {
		c.data.method = "OpenEdit";
		c.data.sys_id = del_id;
		$scope.server.update().then(function(){
			c.data.method = "Edit";
			c.modalInstance = $uibModal.open({
				templateUrl: 'modalTemplate',
				scope: $scope
			});
		});
	}`

When the server update occurred it would pass in the sys_id to the server for the content to load and then populate that into the modal. Hope this helps is what you are after

**Comment by mattifh** [comment]
Thank you!
That's exactly what I am trying to do. Pass the sys_id of the item clicked to the server, so the widget can be opened with that Id on the modal. 

I added your code to mine and for some reason the sys_id is not being passed to the server. This is my current code:
`c.articleModal = function(articleID) {
  c.data.kb_sys_id = articleID;
	$scope.server.update().then(function(){ 
		instance1 =  $uibModal.open({
			templateUrl: 'kb_modal_contextual.html',
			scope: $scope
		})
		}) 
	}`

**Comment by mattifh** [comment]
Actually, I figured where my problem was. Thank you for providing your sample code.

**Comment by patrickw14** [comment]
Closing because issue seems resolved - feel free to reopen if not
