### ISSUE TITLE
How do I build a Header Menu List?

### ISSUE THREAD

**Issue by reginabautista** [service-portal/documentation#129]
Hi everyone, I am trying to build a list for the Header Menu similar to the "My Requests" menu (screenshot). However for some reason the array that I have built is not displaying on the menu. Could you please help me out how I can accomplish this? Thanks -Regina

![image](https://cloud.githubusercontent.com/assets/22941187/19528585/8285038e-9624-11e6-88f7-71485194054f.png)

Here's the code:
Menu Item = Reports
Type = Scripted List
 
var items = [];
 
items.push("My Open Items");
items.push("My Closed Items");
items.push("All Items");
items.push("My Groups Items");
items.push("My Group's Tasks");
 
data.items = items;

**Comment by reginabautista** [comment]
Please disregard, I got it. I created menu items and they worked perfectly. Thanks for the tip.

**Comment by patrickw14** [comment]
Nice! 👍
