### ISSUE TITLE
Data table bugs

### ISSUE THREAD

**Issue by mattifh** [service-portal/documentation#130]
Either I am missing on how to configure a data table, or there are really some serous bugs. Other people have reported this on the community as well and I hope someone from Service Portal team can provide some answers. Here are the list of questions and issues:

- What are the differences between Data Table and Data table from instance definition?

- Data table ignores the title. It simply pulls the plural name of the table.

- Data table ignores the fields set: it defaults to the mobile view of the reference table

- Data table ignores the following options: keyword search, breadcrumb, Header, Footer

- Data table doesn't have any options to set which page to redirect to upon clicking on a record. By default redirect to the form view of the record. The link only works on Data table from instance definition. 

You can find more detail on the same issues reported by several other user from these two inks:

https://community.servicenow.com/message/938460#938460
https://community.servicenow.com/message/1006938#1006938

**Comment by iamwill** [comment]
Hello, yes the datatable widget and datatable from instance vary as you have noticed. The datatable widget was only ever meant to be embedded by other widgets. Please use Data Table from instance definition whenever you need to drop a widget on a canvas using the designer.

**Comment by mattifh** [comment]
Will,
Thank you for clarifying that. What about the other issues that I mentioned. Specifically:
Ignoring Title
Keyword Search
Breadcrumb
Header
Footer
Panel color
And lastly, is there a way to change the link behavior? Similar to how you can set that on simple list?
