### ISSUE TITLE
spModal - load widget-form to create new record

### ISSUE THREAD

**Issue by tuanjinn** [service-portal/documentation#131]
There is a bug when using spModal and load a **widget-form** to create a new record. Normally passing **sys_id=-1** should do the job, but spModal just show "No record found".

```
spModal.open({
            title: 'Adding new incident',
            widget: 'widget-form',
            widgetInput: { table: 'incident', sys_id: '-1'}
        }).then(function(){
            console.log('widget dismissed');
        });
```

when a correct record sys_id is passed in, the modal show the correct editing form.
Any clue?

**Comment by iamwill** [comment]
That looks like a bug. It appears that if you are embedding the form and passing sys_id=-1 then it doesn't work.

If you clone the form widget here is the fix.

Replace this:

		if (input._fields)
			result = $sp.saveRecord(input.table, input.sys_id, input._fields);

		if (input.sys_id == '-1'){
			data.sys_id = result.sys_id;
			data.isNewRecord = true;
		}


With this:

		if (input._fields) {
			result = $sp.saveRecord(input.table, input.sys_id, input._fields);
			data.sys_id = result.sys_id;
		}

		if (input.sys_id == '-1')
			data.isNewRecord = true;

**Comment by thijsdaemen** [comment]
Thanks @iamwill! Any idea when and if this will be fixed in a release or patch?

**Comment by chimteganesh** [comment]
Hi,

I tried the above code. However its not working ass expected for scoped application.

**Comment by tuanjinn** [comment]
@chimteganesh That's not gonna just work, when you clone the widget, there are more stuffs needed to be fixed (can't remember now). So it's quite normal that you couldn't have it worked right away.
