### ISSUE TITLE
NotificationMessage method no longer available?

### ISSUE THREAD

**Issue by jeff-servicenow** [service-portal/documentation#132]
In the regular UI, I am able to display a UI notification using the NotificationMessage() method. From the service portal, I'm getting **ReferenceError: 'NotificationMessage' is undefined** from the console.

Is there a way to display a UI notification in the SP that will not fade away and allow the user to manually close it?

Thanks,
Jeff

**Comment by deconroy** [comment]
Hi Jeff,

I saw in another thread this is not currently possible, but it was mentioned it is being considered for a future release.

What you could do is build your own relatively easily using something like the angular UI bootstrap alerts: https://angular-ui.github.io/bootstrap/#/alert

Hope this helps.

Dan

**Comment by patrickw14** [comment]
^ This is correct, sticky notifications are not currently supported by the built-in notifications in Service Portal, but building your own is of course possible.

**Comment by CapaJC** [comment]
It's something we plan to add, but we don't have a target release yet for it. We also want to add a "unique" message call (if the same unique message gets added multiple times, it will only show up once), mirroring capabilities in the other side of the house.
