### ISSUE TITLE
[$parse:syntax] Syntax Error: 

### ISSUE THREAD

**Issue by mattifh** [service-portal/documentation#133]
I have this code in my HTML:
`<sp-panel ng-if="data.kbIsvalid" title="{{options.knowledge_title}}">`

Which populates the panel title with a value passed from schema options. It works with no issues on Helsinki patch 4 and 5, but not on patch 2. It trows the above error. Any idea why this happens?

**Comment by patrickw14** [comment]
So I understand - it does NOT work on patch 2? Could you please post the entire widget code?

**Comment by mattifh** [comment]
I replaced "<sp-portal>" with Bootstrap default panel and I no longer get the error message. This is what I have now:
` <div class="panel panel-default" ng-if="data.kbIsvalid">
      <div class="panel-heading">
    <h3 class="panel-title">{{options.knowledge_title}}</h3>
      </div>`

This is what I had before:

`<sp-panel ng-if="data.kbIsvalid" title="{{options.knowledge_title}}">`

Two questions:
a) Is the Bootstrap version different from patch 2 to 4?
b) What is unique about the "sp-panel" compared to Bootstrap "panel"?

**Comment by patrickw14** [comment]
SP-panel is really just a shorthand wrapper directive for a Bootstrap panel. The code you replaced sp-panel with is essentially what sp-panel is interpreted into anyway, so your replacement is totally OK. And Bootstrap version has not changed between patches
