### ISSUE TITLE
My approval widget pagination

### ISSUE THREAD

**Issue by mattifh** [service-portal/documentation#138]
Hello,
I am trying to add pagination to my approval widget and I am modeling after "Data Table" widget. The pages begin, end, and total works fine, but the page click-through does not. Has anyone done this in the past or can anyone provide any feedback, please?
Below is the widget detail

HTML:
`<div class="panel panel-{{::options.color}} b">
  <div class="panel-heading">
    <h4 class="panel-title"><fa ng-if="::options.glyph.length" name="{{::options.glyph}}" class="m-r-sm" />{{options.panel_title}}</h4>
  </div>
  <div class="panel-body">
    <div ng-if="data.approvals.length == 0">
      ${You have no pending approvals}
    </div>
    <div ng-repeat="approval in data.approvals" class="sp-approval m-b">
      <div class="row">
        <div ng-class="contentColClass">
          <div ng-if="approval.task.number || approval.task.short_description">
            <a ng-href="?id=approval&table=sysapproval_approver&sys_id={{::approval.sys_id}}" title="View approval page">
              <span ng-if="approval.task.number">{{::approval.task.number}}</span>
              <span ng-if="approval.task.number &amp;&amp; approval.task.short_description"> - </span>
              <span ng-if="approval.task.short_description">{{::approval.task.short_description}}</span>
            </a>
          </div>
          <div class="well well-sm">
            <div ng-if="approval.task.opened_by"><label><b>${Requestor:}</b></label> {{::approval.task.opened_by}}</div>
            <div ng-if="approval.task.approver"><label><b>${Approver:}</b></label> {{::approval.task.approver}}</div>
            <div ng-if="approval.task.start_date"><label><b>${Start:}</b></label> {{::approval.task.start_date}}</div>
            <div ng-if="approval.task.end_date"><label><b>${End:}</b></label> {{::approval.task.end_date}}</div>
            <div ng-if="approval.task.price"><label><b>${Price:}</b></label> {{::approval.task.price}}
              <span ng-if="approval.task.recurring_price"><label><b>${Recurring price:}</b></label> {{::approval.task.recurring_price}} {{::approval.task.recurring_frequency}}</span>
            </div>
          </div>
          <div ng-if="approval.items.length == 1">
            <div ng-repeat="item in approval.items">
              <div ng-if="item.variables.length > 0" ng-init="variable_toggle=false">
                <a href="javascript:void(0)" ng-click="variable_toggle = !variable_toggle">
                  <span class="glyphicon"
                        ng-class="{'glyphicon-chevron-down': !variable_toggle, 'glyphicon-chevron-up': variable_toggle}">
                  </span>
                  ${Options}
                </a>
                <div ng-repeat="variable in item.variables" ng-if="variable_toggle">
                  <label class="text-muted">{{::variable.label}}</label>
                  <div>{{::variable.display_value}}</div>
                </div>
              </div>
            </div>
          </div>

          <div ng-if="approval.variables.length > 0" ng-init="variable_toggle=false">
            <a href="javascript:void(0)" ng-click="variable_toggle = !variable_toggle">
              <span class="glyphicon"
                    ng-class="{'glyphicon-chevron-down': !variable_toggle, 'glyphicon-chevron-up': variable_toggle}">
              </span>
              ${Options}
            </a>
            <div ng-repeat="variable in approval.variables" ng-if="variable_toggle">
              <label>{{::variable.label}}</label>
              <div>{{::variable.display_value}}</div>
            </div>
          </div>
        </div>

        <div ng-if="!options.portal" class="col-sm-2">
          <button name="approve" ng-if="approval.state == 'requested'" class="btn btn-primary btn-block" style="border-width:1px;" ng-click="approve(approval.sys_id);">${Approve}</button>
          <button name="reject" ng-if="approval.state == 'requested'" class="btn btn-default btn-block" ng-click="reject(approval.sys_id);">${Reject}</button>
          <button ng-if="approval.state == 'approved'" class="btn btn-success btn-block">{{approval.stateLabel}}</button>
          <button ng-if="approval.state == 'rejected'" class="btn btn-danger btn-block">{{approval.stateLabel}}</button>
          <button ng-if="approval.state != 'requested'" class="btn btn-default btn-block" style="visibility:hidden">{{approval.stateLabel}}</button>
        </div>
        <div ng-if="options.portal && approval.state == 'requested'" class="col-xs-6">
          <button name="reject" class="btn btn-default btn-block" ng-click="reject(approval.sys_id);">${Reject}</button>
        </div>
        <div ng-if="options.portal && approval.state == 'requested'" class="col-xs-6">
          <button name="approve" class="btn btn-primary btn-block" ng-click="approve(approval.sys_id);">${Approve}</button>
        </div>
        <div ng-if="options.portal && approval.state != 'requested'" class="col-xs-12">
          <button ng-if="approval.state == 'approved'" class="btn btn-success btn-block">{{approval.stateLabel}}</button>
          <button ng-if="approval.state == 'rejected'" class="btn btn-danger btn-block">{{approval.stateLabel}}</button>
        </div>
      </div>
    </div>
   <div class="panel-footer" ng-hide="options.hide_footer" ng-if="data.row_count">
      <div class="btn-toolbar m-r pull-left">
        <div class="btn-group">
          <a ng-disabled="data.p == 1" href="javascript:void(0)" ng-click="setPageNum(data.p - 1)" class="btn btn-default"><i class="fa fa-chevron-left"></i></a>
        </div>
        <div ng-if="data.num_pages > 1 && data.num_pages < 20" class="btn-group">
          <a ng-repeat="i in getNumber(data.num_pages) track by $index" ng-click="setPageNum($index + 1)" href="javascript:void(0)" ng-class="{active: ($index + 1) == data.p}" type="button" class="btn btn-default">{{$index + 1}}</a>
        </div>
        <div class="btn-group">
          <a ng-disabled="data.p == data.num_pages" href="javascript:void(0)" ng-click="setPageNum(data.p + 1)" class="btn btn-default"><i class="fa fa-chevron-right"></i></a>
        </div>
      </div>
      <div class="m-t-xs panel-title">${Rows {{data.window_start + 1}} - {{ mathMin(data.window_end,data.row_count) }} of {{data.row_count}}}</div>

      <span class="clearfix"></span>
    </div>
</div>
  </div>`

Client:
`function ($scope, spUtil, snRecordWatcher, amb) {
  $scope.buttonColClass = "col-sm-2";
  $scope.contentColClass = "col-sm-10";
  if ($scope.options.portal) {
    $scope.buttonColClass = "col-xs-12";
    $scope.contentColClass = "col-xs-12";
  }
  $scope.data.op = "";
  snRecordWatcher.initList("sysapproval_approver", "state=requested^approver=" + window.NOW.user_id);

  function get() {
    spUtil.update($scope);
  }

	$scope.$on('record.updated', function(name, data) {
		get();
	})

  $scope.approve = function(id) {
    $scope.data.op = "approved";
    $scope.data.target = id;
    get();
  }

	$scope.reject = function(id) {
		$scope.data.op = "rejected";
		$scope.data.target = id;
		get();
	}
	$scope.setPageNum = function(num) {
		console.log("page number:", num);
		$scope.data.p = num;
		getData(true);
	}
	
	function getData(updatePath) {
		var f = $scope.data;
		spUtil.update($scope).then(function(data) {
					
			initRecordWatcher(f.table, f.filter);
		});
	}
	
	var watcher;
	function initRecordWatcher(table, filter){
		if (watcher)
			watcher.unsubscribe();

		if (table && filter) {
			var watcherChannel = amb.getChannelRW(table, filter);
			amb.connect();
			watcher = watcherChannel.subscribe(function() {
				spUtil.update($scope)
			});
		}
	}

}`

Server:
`if (input && input.op) {
	var app = new GlideRecord("sysapproval_approver");
	if (app.get(input.target)) {
		app.state = input.op;
		app.update();
	}
}

var gr = new GlideRecord('sysapproval_approver');
var encodedQuery = 'approver=javascript:getMyApprovals()';
var qc1 = gr.addQuery("state", "requested");
if (input)
	qc1.addOrCondition("sys_id", "IN", input.ids);
gr.addEncodedQuery(encodedQuery);
gr.orderByDesc('sys_created_on');
gr.setLimit(50);
gr.query();
var count = gr.getRowCount();

//Pagination
data.p = data.p || 1;
data.p = parseInt(data.p);
data.window_size = data.window_size || 3;
data.page_index = data.p - 1;
data.window_start = data.page_index * data.window_size;
data.window_end = (data.page_index + 1) * data.window_size;
gr.chooseWindow(data.window_start, data.window_end);
gr._query();

data.row_count = count;
console.log("Row count: " + data.row_count);
data.num_pages = Math.ceil(data.row_count / data.window_size);

var approvals = [];
var ids = [];
while (gr.next()) {
	var task = getRecordBeingApproved(gr);
	if (!task.isValidRecord())
		continue;

	ids.push(gr.getUniqueValue());
	var t = {};
	t.number = task.getDisplayValue();
	t.short_description = task.short_description.toString();
	if (task.isValidField("opened_by") && !task.opened_by.nil())
		t.opened_by = task.opened_by.getDisplayValue();

	// requestor >> opener
	if (task.isValidField("requested_by") && !task.requested_by.nil())
		t.opened_by = task.requested_by.getDisplayValue();

	// author >> opener
	if (task.isValidField("author") && !task.author.nil())
		t.opened_by = task.author.getDisplayValue();

	// Delegate approver
	if (gr.isValidField("approver") && gr.approver.toString() != gs.getUserID().toString())
		t.approver = gr.approver.getDisplayValue();

	t.start_date = task.start_date.toString();
	t.end_date = task.end_date.toString();
	t.table = task.getLabel();
	if (task.getValue("price") > 0)
		t.price = task.getDisplayValue("price");

	if (task.getValue("recurring_price") > 0)
		t.recurring_price = task.getDisplayValue("recurring_price");

	t.recurring_frequency = task.getDisplayValue("recurring_frequency");

	var items = [];
	var idx = 0;
	var itemsGR = new GlideRecord("sc_req_item");
	itemsGR.addQuery("request", task.sys_id);
	itemsGR.query();
	if (itemsGR.getRowCount() > 1)
		t.short_description = itemsGR.getRowCount() + " requested items";

	while (itemsGR.next()) {
		var item = {};
		item.short_description = itemsGR.short_description.toString();
		if (itemsGR.getValue("price") > 0)
			item.price = itemsGR.getDisplayValue("price");
		if (itemsGR.getValue("recurring_price") > 0) {
			item.recurring_price = itemsGR.getDisplayValue("recurring_price");
			item.recurring_frequency = itemsGR.getDisplayValue("recurring_frequency");
		}
		if (itemsGR.getRowCount() == 1) {
			item.variables = $sp.getRecordVariablesArray(itemsGR);
			t.short_description = itemsGR.short_description.toString();
		}

		items[idx] = item;
		idx++;
	}

	var j = {};
	j.sys_id = gr.getUniqueValue();
	j.table = gr.getRecordClassName();
	j.task = t;
	if (task)
		j.variables = $sp.getRecordVariablesArray(task);

	j.items = items;
	j.state = gr.getValue("state");
	j.stateLabel = gr.state.getDisplayValue();
	approvals.push(j);
}
data.ids = ids;
data.approvals = approvals;

function getRecordBeingApproved(gr) {
	if (!gr.sysapproval.nil())
		return gr.sysapproval.getRefRecord();

	return gr.document_id.getRefRecord();
}`

**Comment by hardik2038** [comment]
I have implemented it. Check it out at

https://share.servicenow.com/app.do#/detailV2/51cb27b713daa2000de935528144b0f8/overview

- Hardik Vora

**Comment by mattifh** [comment]
Thanks,
Good work on your widget.
