### ISSUE TITLE
AMB

### ISSUE THREAD

**Issue by jonathanjacob** [service-portal/documentation#14]
Is AMB/Record watcher documented? I can't seem to find it... I do see it used a bit in the "Data tables" widget.

Thanks!
Jonathan

**Comment by patrickw14** [comment]
Not yet - we'll get that up on the repo very soon. Until then, you can see some example usage both in the Data Table widget and the Simple List widget.

Cheers!

**Comment by jonathanjacob** [comment]
@patrickw14 Thanks! looking forward to it.

**Comment by patrickw14** [comment]
@jonathanjacob I've added some documentation on Record Watch [here](https://github.com/service-portal/documentation/blob/master/documentation/widget_record_watch.md). Hopefully you find it helpful!

Cheers
