### ISSUE TITLE
Variables Reference Qualifiers on Portal

### ISSUE THREAD

**Issue by mattifh** [service-portal/documentation#140]
It seems that Service Portal does not honor the references qualifiers for variables type of reference and list collectors. Is this by design or a bug? This work as expected on the default UI.

**Comment by davidmckenzie** [comment]
It seems to work here, we have a few catalog items with advanced qualifiers on list collectors. It's worked for me on both the 'form' widget and the default catalog item widget.

Could you provide more info on what you're seeing?

**Comment by mattifh** [comment]
I am using simple reference qualifier which are simply a query filter. I've done some more testing and it seems that this is only unique to Order Guides in Service Portal. Do you have any order guide that you can test this with?

**Comment by mattifh** [comment]
It seems this was a bug that was addressed on Helsinki patch 5.
