### ISSUE TITLE
jQuery compatibility in Service Portal

### ISSUE THREAD

**Issue by mattifh** [service-portal/documentation#146]
I am trying to port some of my dynamic contents from CMS to the SP and most of them used jQuery. In CMS I used to use the jQuery in noneconflict zone. How can we achieve that in Service Portal? Where should we declare the noneconfict variable? It is my understanding that "$" is reserved for angular. 

_Also, I'd like an answer tot he followings:
Does Service Portal supports jqLite? 
How do we set an order, so jquery loads before the angularJS?_

**Comment by deconroy** [comment]
jQuery can be used as $ or jQuery on the client side. No need for noconflict, as we are not using PrototypeJS on SP.

Some variables reserved for angular do have a "$" prefix. But not "$" by itself.

**Comment by mattifh** [comment]
Thanks for your response. Were you able to successfully run jQuery on a widget? No matter how I format it, I continue to get errors on the run time.

**Comment by deconroy** [comment]
Yes I have, what version of Helsinki are you on? Would you mind posting an extract of the code you are having issues with?

**Comment by schusterf** [comment]
I was able to run jQuery just like Dan said, via "jQuery" on the client.

Here's the HTML:
`<h2>This is a heading</h2>

<p>This is a paragraph.</p>
<p id="test">This is another paragraph.</p>

<button ng-click="c.setHeight()">jQuery Height Trigger</button>
<button ng-click="c.hideAndShow('hide')">jQuery Hide Element</button>
<button ng-click="c.hideAndShow('show')">jQuery Show Element</button>
`

And here's the client controller script:
`function() {
	/* widget controller */
	var c = this;

	c.setHeight = function() {
		jQuery("#test").height("300");
	};

	c.hideAndShow = function(action) {
		if(action == "hide") {
			jQuery("#test").hide();
		} else {
			jQuery("#test").show();
		}	
	};
}`

**Comment by mattifh** [comment]
Frank and Dan,
Thank you both for providing feedback. Im not sure what I am doing wrong, but my jQuery code simply doesn't run. Here is my HTML and controller.

```
<div class="scroll-top-wrapper">
	<span class="scroll-top-inner">
    <i class="fa fa-2x fa-arrow-circle-up"></i>
  </span>
</div>
```

```
jQuery(document).on('scroll', function(){
	if(jQuery(window).scrollTop() > 100) {
		jQuery('.scroll-top-wrapper').addClass('show');
	}else{
		jQuery('.scroll-top-wrapper').removeClass('show');
	}
});

jQuery('.scroll-top-wrapper').on('click', scrollToTop);

function scrollToTop() {
	verticalOffset = typeof(verticalOffset) != 'undefined' ? verticalOffset : 0;
	element = jQuery('body');
	offset = element.offset();
	offsetTop = offset.top;
	jQuery('html, body').animate({scrollTop: offsetTop}, 500, 'linear');
```

**Comment by deconroy** [comment]
Hmmmm, I can't tell just by looking at it what is going wrong, might try have a look when I get a few minutes. Does the code work if you try it outside of the Service Portal?

It might be worth trying to convert some of the code to angular - I always think it is a good rule of thumb to only use jQuery in an angular site as a last resort.

First of all, can you change the ".on('click')..." to use ng-click? And the ".on('scroll').." to use something like this directive: http://thenikso.github.io/angular-inview/ - I have successfully used this in SP before to enable infinite scrolling.

You could also try something like `$window.scrollTo(0, angular.element('put here your element').offsetTop); ` to scroll to the part of the page you want.

All that being said however, I have used jQuery to autoscroll to the bottom of the page in SP before, using similar code to what you have - so it should work. Is your scrollToTop function being fired? Seeing any JS errors? Is the jQuery(document).on('scroll'... bit firing?

The jQuery code you have pasted - I assume this is inside an angular controller function?

**Comment by yagoferrer** [comment]
Directives are used for DOM manipulation not controllers. You should create a directive for this, and use events to communicate with the widget and hide and show things.
