### ISSUE TITLE
Setting the default query in sn-record-picker

### ISSUE THREAD

**Issue by puneet94** [service-portal/documentation#152]
Can somebody provide an example or sample syntax for using **default-query** field in sn-record-picker.
I tried to write a query for sys_user table. But doesn't seem to work.

<sn-record-picker field="userField"  table="'sys_user'" **default-query="u_type='Teacher'"** value-field="'sys_id'" search-fields="'first_name'" page-size="10" >
            </sn-record-picker>

I want to filter those users whose u_type is equal to "Teacher". 
What would be the correct syntax for it?

**Comment by hardik2038** [comment]
Quotes are misplaced.  Use:  default-query="'u_type=Teacher'"

**Comment by puneet94** [comment]
and what would be the syntax for a complex query with OR and AND conditions. Something like type = techer and age>18

**Comment by CapaJC** [comment]
Here's an easy trick to build an encoded query: go to a list in the normal UI, build your filter, then right-click the filter breadcrumb and select Copy Query. The encoded query will be copied to your clipboard. 

--J

On Nov 24, 2016, at 7:15 PM, Puneet Mahendra <notifications@github.com> wrote:

and what would be the syntax for a complex query with OR and AND conditions. Something like type = techer and age>18

**Comment by puneet94** [comment]
Thanks guys. That solves the issue.
