### ISSUE TITLE
c.server.update() and $sp.getParameter

### ISSUE THREAD

**Issue by jonathanjacob** [service-portal/documentation#158]
When c.server.update() is called from the client script, it seems like $sp.getParameter does not run.

**Comment by mozrat** [comment]
Hi @jonathanjacob - that is correct. You should use the input parameter when the server script is called on subsequent cycles

for example

`data.sys_id = $sp.getParameter('sys_id') || input.sys_id`

**Comment by CapaJC** [comment]
At some point the URL parameters *will* be made available the 2nd time through - mozrat's code will still work in that case.

**Comment by jonathanjacob** [comment]
Got it thanks @mozrat ! @CapaJC if I submit a pull request documenting this would it be merged in? It may be useful to know, in case someone else is facing the same issue.

**Comment by CapaJC** [comment]
Hmm, I don't know - I'm not familiar w/ how that's managed. Hopefully someone else can chime in here on that.

**Comment by jonathanjacob** [comment]
Oh my bad, I thought you were part of that... I will go ahead and submit it anyway.
