### ISSUE TITLE
Missing Script Includes and Processor Info

### ISSUE THREAD

**Issue by jbwilmoth** [service-portal/documentation#16]
I am not seeing any details on how to enable or add the SPEntryPage() and SPLoginRedirectURL() SI's or the /spnavto processor. Are these hidden in the platform somewhere?

I greatly appreciate all the hard work you all have done to make this repo happen and I will continue to contribute as much as possible. Thank You!

-Joe

**Comment by nathanfirth** [comment]
They did not make it into Patch 0, but should be available with Patch 1.

**Comment by jbwilmoth** [comment]
Thank you Nathan!
