### ISSUE TITLE
Record Watch

### ISSUE THREAD

**Issue by toddstocking** [service-portal/documentation#18]
Does spUtil.recordWatch only work with specific tables?  I can successfully get it to work on "Incident" but not "ts_query_kb" and was curious if there is anything specific preventing this?

**Comment by patrickw14** [comment]
Hi Todd,

Tables that are (periodically) subject to a high frequency of database events are blacklisted to prevent event storms. Most of the text search tables have been blacklisted by record watcher (this isn't something that falls under the scope of Service Portal).

Let me know if you have any other questions!
