### ISSUE TITLE
$scope.page.g_form.setValue

### ISSUE THREAD

**Issue by jboyland** [service-portal/documentation#186]
Hi Guys, 

I have used $scope.page.g_form.setValue on a record producer, however this does not work when dealing with a page that is set up to use the form widget, E.G if the ticket page used the OOB form widget. Is there a way to push data from a widget into the form widget? 

Thanks

**Comment by jboyland** [comment]
*BUMP* anyone have any information?

**Comment by dangibbardsn** [comment]
OOB Form Widget just uses standard g_form (As long as UI Type is set correctly)

**Comment by zzjasonzz** [comment]
Not sure if there is a way OOB but you could customize the form widget to listen for a broadcast and take action, and then broadcast a message from the other widget with the data you need in the form widget.

**Comment by jboyland** [comment]
Thanks Jason, I was trying to avoid creating a copy of the form widget but I may have to go down that path.
