### ISSUE TITLE
Service Portal - Page designer does not play nice with shared services

### ISSUE THREAD

**Issue by Quixomatic** [service-portal/documentation#187]
Creating an angular provider - service and then including that in multiple widgets so that you can use a single shared service with shared functionality across those widgets works great and just like normal when actually loading a page in service portal.
 
However, after injecting that service into your widget function `function ($scope, spUtils, SharedService) { ... }` the widgets will throw an error if you're in the page designer. The widgets still work perfectly elsewhere, but if you want to drag them around or change the options that will not be possible. There are two errors that get thrown only in the page designer:
 
```
TypeError: config[provider.type] is not a function
    at Object.providers (js_includes_sp_designer.jsx:74283)
    at Object.loadDirective (js_includes_sp_designer.jsx:72585)
    at js_includes_sp_designer.jsx:76421
    at processQueue (js_includes_sp_designer.jsx:13849)
    at js_includes_sp_designer.jsx:13864
    at Scope.$eval (js_includes_sp_designer.jsx:14422)
    at Scope.$digest (js_includes_sp_designer.jsx:14329)
    at Scope.$apply (js_includes_sp_designer.jsx:14449)
    at done (js_includes_sp_designer.jsx:11104)
    at completeRequest (js_includes_sp_designer.jsx:11216)
(anonymous) @ js_includes_sp_designer.jsx:11973
```
 
```
js_includes_sp_designer.jsx:11973 Error: [$injector:unpr] Unknown provider: SharedServiceProvider <- SharedService
http://errors.angularjs.org/1.5.8/$injector/unpr?p0=SharedServiceProvider%20%3C-%20SharedService
    at js_includes_sp_designer.jsx:6202
    at js_includes_sp_designer.jsx:8068
    at Object.getService [as get] (js_includes_sp_designer.jsx:8188)
    at js_includes_sp_designer.jsx:8073
    at getService (js_includes_sp_designer.jsx:8188)
    at injectionArgs (js_includes_sp_designer.jsx:8209)
    at Object.invoke (js_includes_sp_designer.jsx:8225)
    at $controllerInit (js_includes_sp_designer.jsx:10657)
    at nodeLinkFn (js_includes_sp_designer.jsx:9945)
    at compositeLinkFn (js_includes_sp_designer.jsx:9521)
```
 
These errors are not something that are easy to stacktrace or for me to fix since I don't have access to js_includes_sp_designer.jsx. Is there someone that can look into this further? I'd definitely prefer to communicate between widgets with a shared service rather than broadcasting through rootScope if possible.
 
EDIT:
I would also like to mention that SharedService is properly injected into the widget if not in the Page Designer (ie on some page in Service Portal and you're viewing it like normal). I think that was said earlier in my comment, but I wanted to make that clear. There are no errors outside of page designer.

**Comment by patrickw14** [comment]
Right you are - it looks like this is definitely a problem on our end. We'll investigate - if you would like to track the progress of the issue, you can take a look at PRB827724 on HI. https://hi.service-now.com/problem.do?sys_id=b2ad02c8db59b2c84fc2f4621f9619cb&sysparm_view=&sysparm_domain=null&sysparm_domain_scope=null

Thank you so much for communicating this to us!

**Comment by patrickw14** [comment]
Should have mentioned - please go ahead and reopen this issue if there is any other advice you need.

**Comment by Quixomatic** [comment]
@patrickw14 Link doesn't seem to be pointing to a opened ticket.

**Comment by iamwill** [comment]
I just ran into the same problem. Here is a workaround. Add this as a JS dependency to one of your widgets on the page, set it to load on page load.

try {
	angular.module('ng_spd').config(function(lazyLoaderProvider, $provide, $compileProvider, $controllerProvider){
		lazyLoaderProvider.set({
			register: $controllerProvider.register,
			directive: $compileProvider.directive,
			factory: $provide.factory,
			value: $provide.value,
			service: $provide.service
		});
	});
}catch(e){}

**Comment by royaltwets** [comment]
@iamwill  - Thanks.  Fix is working well for me.  I've put the dependency into a new and otherwise empty widget instead of one of the exisiting widgets on the page.  That way I can put a single instance of this widget onto my affected pages without having to change anything else.  Then when I'm done designing the page, I can delete the widget instance so that the dependency isn't loaded unnecessarily.   Will also mean that when this defect is fixed in the base product, I won't have to change anything at all to benefit from it.

**Comment by Quixomatic** [comment]
That workaround seems like a great fix, still wish this issue would be reopened and a HI ticket opened as well. @patrickw14

**Comment by jbsaff** [comment]
I'm getting the same error, but it's occurring on the ServicePortal page as well, not just in Page Designer. I've got a shared service, used by multiple widgets in the page. I get the error:
`TypeError: config[provider.type] is not a function`

If I navigate away via my application, then return to the page, the error doesn't occur and the page loads properly. A new page load, or a refresh of the page with a clear cache, always shows the error.  It seems like the provider isn't available on the first load, but is when I navigate back without a refresh.

Any ideas or suggestions?
