### ISSUE TITLE
Use of ref_ac_columns on reference variable

### ISSUE THREAD

**Issue by jfbenedict** [service-portal/documentation#188]
I am trying to display additional attributes from the sys_user table on a catalog item variable.  In the native UI catalog this works by setting the ref_ac_columns within the variable attributes (my values set to ref_ac_columns=name;email).

Here is how it looks in the native UI:
![image](https://cloud.githubusercontent.com/assets/20973933/23462475/3414549a-fe4b-11e6-86dd-2b838eff4627.png)

But when viewing with in the Service Portal all I see is the Name attribute, see below:
![image](https://cloud.githubusercontent.com/assets/20973933/23462503/4b79127e-fe4b-11e6-9622-45a39188046c.png)

Is there a way to manipulate the fields that display in the reference drop-down?  The reason for this is the environment has many users with the same name and I need a way to display the differences.

**Comment by CapaJC** [comment]
Pretty sure that attribute is supported in recent versions - what version are you on?

**Comment by CapaJC** [comment]
Helsinki Patch 4 got a fix where if a field wasn't one of the columns in the list for the referenced table (Default view, I believe), it wouldn't show as an additional columns using ref_ac_columns. That was PRB692894

**Comment by jfbenedict** [comment]
CapaJC - I am running on Istanbul (glide-istanbul-09-23-2016__patch0-10-05-2016).  

Is it possible that it was fixed in Helsinki and has been re-broken with Istanbul?

**Comment by jfbenedict** [comment]
I figured out my issue.  I had the variable attribute set to:
ref_ac_columns=email

And changing it to the following resolved my issue:
ref_auto_completer=AJAXTableCompleter,ref_ac_columns=email

Looks like the ref_auto_completer attribute is needed
