### ISSUE TITLE
Is there a known issue with a date variable and accepting non-date values?

### ISSUE THREAD

**Issue by jfbenedict** [service-portal/documentation#189]
I was testing a mandatory date type of variable on a catalog item within the service portal and it allows me to put in invalid date values and submit the request.

Here is an example:
![image](https://cloud.githubusercontent.com/assets/20973933/23485723/f8e3e4e0-fe99-11e6-8bc3-66772344d450.png)

This is on Istanbul

**Comment by CapaJC** [comment]
Yeah, if you use the picker it'll just handle it (after HP7 or so for custom date formats), but a user manually typing a date is currently expected to enter the correct format.

Tracked in PRB759180

**Comment by jfbenedict** [comment]
CapaJC - Thanks for the quick reply.

In case you are interested here is my current workaround for this.  I created my own copy of the Catalog Item Widget and updated the triggerOnSubmit function to the following:

$scope.triggerOnSubmit = function(){
	var aInvalidVars = [];
	$formErrors = $('.has-error .form-control');
	$formErrors.each(function() {
		var fieldID = $(this).attr('name');
		if ( g_form.isMandatory(fieldID)) {
			aInvalidVars.push(g_form.getLabelOf(fieldID));
		}
	});
		
	if ( aInvalidVars.length > 0 ) {
		alert('"'+ aInvalidVars.join(',') + '" contains an invalid value, please correct these field values');
		return;
	}
		
	if (g_form)
		g_form.submit();
};
