### ISSUE TITLE
sn-choice-list directive

### ISSUE THREAD

**Issue by Sophismata** [service-portal/documentation#196]
For instances on Helsinki, what's expected for the "field" and "option" attributes in this directive?
<instance-name>/scripts/app.$sp/directive.snChoiceList.js does not return anything.

If that directive is inappropriate to generate a select2 choice list, what should be used instead?

**Comment by jacebenson** [comment]
Might be helpful to bring in the information from this thread https://community.servicenow.com/thread/257924

**Comment by jacebenson** [comment]
According to the post...
`
//client script
 c.genderchoice = [{
  genderdisplay: "Male",
  gendervalue: 'M'
  }, {
  genderdisplay: 'Female',
  gendervalue: 'F'
  }];
 
  c.genderchoicelistoption = {
  hideSearch: true,
  placeholder: "Gender"
  };`

`

      <sn-choice-list sn-model="c.gender" sn-options="c.genderchoicelistoption" sn-value-field="gendervalue" sn-text-field="genderdisplay" sn-items="c.genderchoice"></sn-choice-list>
`

**Comment by Sophismata** [comment]
Thanks!
