### ISSUE TITLE
Sending Data from a Widget embedded in a Record Producer

### ISSUE THREAD

**Issue by frank815** [service-portal/documentation#202]
Looking for best practices or if anyone has a better solution. 

Currently in Helsinki I've built a record producer that creates an incident. I've also had to build a widget that you can add multiple forms dynamically. All this is fine and works perfectly with no issues. 

The is issue when trying to send data from the widget back to the RP to record the data. There is no connection ($scope, document, etc...) between the widget and the RP. My solution was to push the data to the "top" frame of the window object and access it through the RP which works but seems kinda wrong.

My question is this best practice for this solution or is there a better option out there?

**Comment by NYancer3** [comment]
If you use a widget embedded in a variable (like you would with a macro) then you should have access to g_form within that widget's client controller. So if you're trying to pass data into the record producer from a widget that is outside the record producer, you should be able to use $rootScope.$broadcast to pass data to the widget variable. Then, in the widget variable you can listen for the event and update whichever form fields you need via $scope.page.g_form. Using events is the best way to pass data around, I've found.

Hope that helps.

**Comment by frank815** [comment]
This is a little simpler than that. 

I have a record producer (Desktop Broken) with a widget that i added with macro. The widget contains inputs that the user fills out. When I submit the RP it doesn't submit the inputs that are the widget. 

How do i get the data from the input fields on the widget into the record producer?

**Comment by chrisburks-kg** [comment]
The part you need from @NYancer3's response is the $scope.page.g_form. Using this method is how the widget talks to the RP. However, there needs to be a variable or correlating variables on the RP side to hold the data. These can be hidden or visible. Then you can collect that data normally as you would in creating a RP.
For example if you had a variable on your RP and it's name is "name" and you had a field in your widget with a field with ng-model="requestor" that held a value you can collect the data from the field on the widget and pass it to the field in the RP like so:  
`$scope.page.g_form.setValue('name', $scope.requestor)`

_(note: you may need a function or something to kick that off depending upon how the widget is scripted)_ 

Of course this is not a great use case but it is a basic example of how to pass the data from a widget embedded in a record producer to the record producer.

**Comment by NYancer3** [comment]
Thanks @chrisburks-kg, I tried to email back a similar answer, but it didn't update...

The missing piece is definitely a place to put the data when you save the record. If the data are complex, you can save it as a JSON string and process it in the RP script. But you have to put it in a variable for it to be saved to the record.

**Comment by frank815** [comment]
@NYancer3 @chrisburks-kg this is exactly what i needed!! thank you! this worked perfectly!
