### ISSUE TITLE
Angularjs app.config via Service Portal

### ISSUE THREAD

**Issue by nrakochy** [service-portal/documentation#204]
Is there any way to access Angular app.config in the Service Portal? Or perhaps a known work-around? 

I am familiar with the options available in Angular Providers. However, `.config` would be helpful for initializing $routeProvider, $http interceptors, etc.

I am following up on [this issue](https://community.servicenow.com/thread/229091). Any help would be greatly appreciated.

**Comment by iamwill** [comment]
See my response on the community site. You can do it but it's not supported so you are on your own in the future.

**Comment by nrakochy** [comment]
I do appreciate the help. Many thanks...
