### ISSUE TITLE
Why do we need "-" before ng-controller 

### ISSUE THREAD

**Issue by jpavanaryan** [service-portal/documentation#209]
ng-controller does not work in Service Portal without "-" before directive name. Why do we need "-"? And why is it different from Angularjs standard syntax.
 
Ex:  <div -ng-controller="incidentSummaryCtrl">
     </div>

**Comment by CapaJC** [comment]
We intentionally remove the ng-controller attribute. Seems like there was a really good reason at the time the change was made.

**Comment by jpavanaryan** [comment]
Do we have any other attributes that were removed?

**Comment by CapaJC** [comment]
Not that I know of or can see in the code, though I have not done an exhaustive investigation. 

On May 5, 2017, at 6:43 PM, Pavan Kumar <notifications@github.com> wrote:

Do we have any other attributes that were removed?
