### ISSUE TITLE
$rootScope

### ISSUE THREAD

**Issue by nick-pike** [service-portal/documentation#21]
Hi Guys, is it possible to get some documentation around $rootScope and sharing data between separate widgets on the same page?

Cheers,
Nick

**Comment by patrickw14** [comment]
Hi Nick,
For $rootscope, I think the Angular docs will probably be most helpful for you - event handling works the same way in Service Portal as it does in any normal Angular app.

We'll add some docs on communication between widgets in general though. Thank you!
