### ISSUE TITLE
Restrict Service catalogue content in SP based on users role. 

### ISSUE THREAD

**Issue by mohansrinivas91** [service-portal/documentation#216]
Hi All,
 
We have got the below  requirement on SP and
 
When a non-ITIL user logs in, on the Service Catalog page they should see BP carousal images in the carousal. Clicking on the images should take the users to the respective form.
Widget Instance- SC Home Carousel
When an ITIL user logs in, on the Service Catalog page they should see the SC IT images in the carousal. Clicking on the images should take the user to the respective form.

**Comment by CapaJC** [comment]
With User Criteria on the sp_instance record this may get easier (with Jakarta), and with current code I'm pretty sure someone else will have something better, but the following would work...

1) put the "itil" role on the existing Carousel sp_instance record, load it w/ the SC IT images
2) clone the carousel widget and name it "nonITIL Carousel", add an IF statement to the server script to make it read: 
if (!gs.hasRole("itil")) // this way ITIL users won't see these
    data.slides = $sp.getRelatedList('sp_carousel_slide','carousel');
3) add a 2nd sp_instance to the Service Catalog page pointing to your new, cloned widget, load it w/ the non-ITIL images

Then each user should see what they need.

Alternately you could add a Condition field to the carousel slide record, and change the Carousel widget to check the Condition before adding each slide to the Data object. That get trickier, but it'd be possible with the right script evaluation API.

**Comment by mohansrinivas91** [comment]
Thanks for the solution Capajc.
