### ISSUE TITLE
g_user equivalent API to be used in client controller for Service portal widget

### ISSUE THREAD

**Issue by deepadokania** [service-portal/documentation#217]
I am trying to get some session data in client controller for which I used var v = g_user.getClientData('test1'); , but I think it is not supported as it gives 'g_user is undefined'. Can any one provide some help on this?

TIA

**Comment by iamwill** [comment]
g_user is only available inside form client scripts like onLoad, onChange, onSubmit.

However you can get access to the data you want from the widget server script and then you can pass it back to your widget to use however you like.

You can use gs.getUser() in the server script.
