### ISSUE TITLE
spModal return select value

### ISSUE THREAD

**Issue by dtrainer** [service-portal/documentation#219]
I'm looking to add a select list in an embedded modal window. I have the modal created with the select list populated but I'm having trouble returning the selected value. I see the value definition that can be used an input but is there an object definition for spModal to use for select boxes or would this require the $uibModal service?

**Comment by iamwill** [comment]
Hello.

Can you share some code or do you want me to? I would use the modal widget but it might be easier for you to share code if you are using the $uibModal service to launch the modal.

**Comment by dtrainer** [comment]
Here is the basic code of the modal. My issue is more that I'm new to angular and modals so I'm unsure how to return the select box value to the primary widget. And I'm not sure this can be accomplished in the spModal wrapper. Thanks!

Primary widget HTML button:
`<button ng-click="c.onChangeSchedule()" id="changeScheduleButton" class="btn btn-default">Change Schedule`

Primary widget Client script loading the modal:
```
function ($scope,spModal) {	
	//$rootScope.$broadcast('sp.update.breadcrumbs', $scope.data.breadcrumbs);
	/* widget controller */
	var c = this;
                c.onChangeSchedule = function(){
		spModal.open({
			title: 'Change Schedule',
			widget: 'bec1438bdbf276009ed8f81d0f96193e',
			widgetInput: { itemID:c.data.itemID }
		}).then(function(){
		});
	}
}
```

Modal HTML:
```
<div>
	<select ng-model="c.selectedSchedule" ng-selected="" ng-options="v.text for (k, v) in data.questions">
  <option value="">Select Type</option>
  </select>
  <p>
    Selected Value Is: {{ c.selectedSchedule.text }}
  </p>
</div>
```

Modal Server Script:
```
(function() {
	/* populate the 'data' object */
	/* e.g., data.table = $sp.getValue('table'); */
	data.questions=[];
	var gr = new GlideRecord('question_choice')
	gr.addQuery('question','bae8a353db727600ab5afd0e0f961909');
	gr.query();
	while(gr.next()){
		var temp = {};	
		$sp.getRecordDisplayValues(temp, gr, 'text,value,sys_id');
		data.questions.push(temp);
	}
})();
```

**Comment by iamwill** [comment]
I can't believe this isn't documented...
One of the options you can use in the spModal.open() method is called **shared**

I changed your code so you can use it, see below:


Primary widget Client script loading the modal:
```
function ($scope,spModal) {	
	var c = this;
	var shared = {};
	c.onChangeSchedule = function(){
		spModal.open({
			title: 'Change Schedule',
			widget: 'bec1438bdbf276009ed8f81d0f96193e',
			widgetInput: { itemID: c.data.itemID },
			shared: shared
		}).then(function() {
			// Shared object was updated
			console.info(shared);
		});
	}
}
```

Modal HTML:

```
<div>
	<select ng-model="c.selectedSchedule" ng-model-options="{getterSetter: true}" ng-options="v.text for (k, v) in data.questions">
  <option value="">Select Type</option>
  </select>
  <p>
    Selected Value Is: {{ c.selectedSchedule() |json }}
  </p>
</div>
```


Modal Client Script:

```
function() {
  var c = this;
	
	var shared = c.widget.options.shared;
	c.selectedSchedule = function setValue(newVal) {
		return angular.isDefined(newVal) ? (shared.schedule = newVal) : shared.schedule;
	}
}
```



The shared object gets put in the embedded widget's options. you can see how you can access it via **c.widget.options.shared**

If you want to submit a pull request with updated documentation when you're done I would love to see what you come up with. Otherwise I can add better documentation when I have more time.

**Comment by iamwill** [comment]
I updated the doc anyway, I'll probably never get around to it another time.

https://github.com/service-portal/documentation/blob/master/documentation/spModal.md#example-5-embedded-widget-with-shared-data
