### ISSUE TITLE
ServicePortal List columns-Display customized fields

### ISSUE THREAD

**Issue by mohansrinivas91** [service-portal/documentation#225]
We have four widgets for requests&incidents and On further clicking on "View all" under each of the above mentioned widget we are displayed the list of incidents and requests for that category. The columns displayed for the widget needs to be corrected, we need to modify/add other fields here but unable to get where they retrieve these fields. Thanks in advance

![image](https://cloud.githubusercontent.com/assets/28778563/26648126/10c04aec-465f-11e7-80b8-aab20b718d06.png)

**Comment by iamwill** [comment]
Are you using the widget "data table from url definition"? if so you can pass the view name as a url parameter: view=my_custom_view

my_custom_view would be the name of a list view you create in the platform.

As a reference, those columns are picked in the following way:
1. If a view is specified use that.
2. If there is a view named "sp"
3. Use the default view.

**Comment by jacebenson** [comment]
Iknow this is after the fact and it isnt' shown in the widget but the default view, is "mobile" so if you cahnge "mobile" view to have your columns you can not specifiy the view still.
