### ISSUE TITLE
getXMLAnswer();//no callback is not working

### ISSUE THREAD

**Issue by jacebenson** [service-portal/documentation#237]
is this supposed to work?  When I try it i get no response in the netowrk and the console shows my stuff as undefiend.  It works with a callback but I'm trying to stop a form submission.

```
function onSubmit() {
	var allow = false;
	var ga = new GlideAjax('x_fair_mobile.Utils');
	ga.addParam('sysparm_name','validateForm');
	ga.addParam('sysparm_service', g_form.getValue('request_service_type'));
	ga.addParam('sysparm_country', g_form.getValue('phone_country'));
	ga.addParam('sysparm_use_policy', g_form.getValue('request_use_policy'));
	ga.addParam('sysparm_authorization', g_form.getValue('account_authorize_transfer'));
	ga.addParam('sysparm_eligible_date', g_form.getValue('phone_eligible_date'));
	ga.addParam('sysparm_requested_for', g_form.getValue('requested_for'));
	var response = ga.getXMLAnswer();
  	g_form.clearMessages();
		g_form.hideAllFieldMsgs();
		var responseObj = JSON.parse(response);
		allow = responseObj.allowSubmit;
		console.log(responseObj);
		if(responseObj.message) {
			g_form.addErrorMessage(responseObj.message);
		}
		for(var prop in responseObj.fields){
			g_form.showFieldMsg(prop, responseObj.fields[prop], 'error');
		}
	  	console.log('allow: ' + allow);
	return allow;
}
  ```
![image](https://user-images.githubusercontent.com/638764/26947945-3611577c-4c5a-11e7-9b33-32c729e85c86.png)

**Comment by CapaJC** [comment]
Synchronous use (without callback) isn't supported in the Mobile scripting environment that Service Portal shares. You should've gotten a warning in your browser console - if you didn't, that's a path we missed when adding warnings

**Comment by jacebenson** [comment]
Weird.  I didn't notice any warnings.  I did notice that on here it says it is supported.
https://github.com/service-portal/documentation/blame/master/documentation/client_scripting.md#L117

I mean, thats great and I found that yea, does not work.  Maybe we should nix this line then.

**Comment by jacebenson** [comment]
And it's been updated.
