### ISSUE TITLE
no-show / mg-hide 

### ISSUE THREAD

**Issue by cterzian** [service-portal/documentation#25]
Whenever we try to add a ng-show to show to a particular div section, ServiceNow automatically adds a ng-hide. This means that all of our cart use cases show up.
 
thanks

**Comment by patrickw14** [comment]
Not sure how or why this would happen - can you give me some sample code so I can reproduce the problem?

**Comment by frankschuster** [comment]
I've worked quite a lot with "ng-show" and couldn't experience any issues. Be sure that your expression is not "falsy". If it is, then it's actually the ng-show directive which adds the "ng-hide" class.

**Comment by cterzian** [comment]
Thanks for the responses guys.  I'm educating myself on Angular now - so I know enough to be more dangerous ;-)  I'm expecting more details from our Partner on the issues and after looking into this myself first, will come back with more educated questions (hopefully).   Cheers!
