### ISSUE TITLE
onChange not working for sn-record-picker directive

### ISSUE THREAD

**Issue by dpatino2** [service-portal/documentation#253]
The onChange argument described in issue #59  is not triggering my function.  When I modify the field, no alert appears.

`<sn-record-picker field="c.user" 
                  table="'sys_user'" 
                  display-field="'name'" 
                  value-field="'sys_id'" 
                  display-fields="'email'" 
                  search-fields="'name'" 
                  onChange="'c.userPicked()'"
                  />`

`
	
	c.userPicked = function(){
		alert('success');
	}
	
`

**Comment by pmuramalla** [comment]
have you tried ng-change ?

**Comment by dpatino2** [comment]
Wow, that actually worked.  I didn't try it since I was working with a directive instead of an actual input field.  Thanks to you and the SN team who kept up with the standard!
