### ISSUE TITLE
access to sc-cat-item 

### ISSUE THREAD

**Issue by cterzian** [service-portal/documentation#26]
We're building a Cart widget.  In order to make the cart pricing responsive to selected options on the request form, we need access to catalog form variables. In Service Portal, within the widget – SC Catalog Item, ServiceNow is using a custom directive by name sc-cat-item.  We do not have access to this directive and we do not know how to read the variables.

**Comment by patrickw14** [comment]
@cterzian I'm not sure what directive you are referring to - can you point to a specific place in the code where that is being referenced?

**Comment by iamwill** [comment]
You have access to that entire model inside your widget. If you're logged into your portal as an admin, take a peek like this:

![screen shot 2016-06-30 at 7 14 59 am](https://cloud.githubusercontent.com/assets/179779/16494154/148df518-3e9d-11e6-9e08-ebdb0529b128.png)

**Comment by cterzian** [comment]
That's a great feature - I'll check it out.

thanks!
