### ISSUE TITLE
Embed Widget Instance

### ISSUE THREAD

**Issue by pwydra23** [service-portal/documentation#28]
Hi,

I understand how to embed a widget, so thank you for the documentation.

Is there a method for embedding a Widget Instance? I want to include an Icon Menu List Widget Instance inside of another Widget, but am not sure how.

Thank you.

**Comment by deconroy** [comment]
Hi Paul,

You can embed a widget instance with the "widget" directive.

A good example of this is in the OOTB "Homepage Search" widget, which embeds an instance of the typeahead search with the line:

<widget rectangle="typeahead_search_header"></widget>

This will grab the widget instance with the id of "typeahead_search_header".

Hope this helps.

Dan

**Comment by pwydra23** [comment]
Excellent, thank you. 

Confusion on my end was the ID field was not visible on all instance types. Just had to add the field to the form for the Icon Menu List type.
