### ISSUE TITLE
OnLoad script event - hide labels

### ISSUE THREAD

**Issue by xxJimxx** [service-portal/documentation#29]
Hello, 
I am unable to hide labels in the portal with:
 		g_form.setDisplay('location_label', false); //  works on platform, not in portal
or
 		g_form.setVisible('location_label', false); // attempt to hide

UI Policies do not seem to be working on the labels either.

Scripts and Policies are set to to UI Type of Both  (Desktop and Mobile)  These work on other types in the portal.

**Comment by xxJimxx** [comment]
Hello, i need to add the variable type of "wide single line of text" to this issue...

**Comment by artemis15** [comment]
Hi,

SP does not support g_form as far as i know. Better to use ng-show or ng-hide

**Comment by xxJimxx** [comment]
The catalog items are still supposed to use g_form.  They do not, or are not supposed to have access, outside of the item container.  Angular methods are blocked as well as jQuery and window/document.

**Comment by frankschuster** [comment]
That is exactly what SP will do - if there is an according "hide" function on the backend, ng-hide will be applied as a class. As you pointed out the important part is the type of the client script, but even with Desktop or Mobile labels definitely won't be hidden, just quickly tested that on one of my instances. Appears to be a bug - @patrickw14: any inside on this?

**Comment by iamwill** [comment]
This will be fixed in HP3.

g_form works just fine in catalog client scripts, and form client scripts. Refer to this page for detailed info:
https://github.com/service-portal/documentation/blob/master/documentation/client_scripting.md
