### ISSUE TITLE
Localization Widget Content

### ISSUE THREAD

**Issue by Snow-Averell** [service-portal/documentation#30]
Unfortunately I can't find any hint about localization in all available SP docs. 
What we need from my point of view are the following things:

- documentation of localization concept
- tools to support localization
- tools to prove localization

In meantime i figured out that there is a concept for localization for widgets: All sections marked like this ${XYZ} are replaced by localized terms stored in the  sys_ui_message table if there is a translation available. I've developed the following widget code to parse all widgets for these sequences and to prompt it:

HTML Template:
`<div class="panel panel-default">
    <div class="panel-heading">List of widgets including text to translate</div>
  	<div class="panel-body">
      <div ng-repeat="item in c.data.items">
          <h3><a ng-href="?id=widget_editor&sys_id={{item.sys_id}}">{{item.name}}</a></h3>
    		<ul><li ng-repeat="temp in item.template">{{temp}}</li></ul>      
      </div>     
    </div>
</div>
`   

Client Script
`function() {
  // widget controller
  var c = this;
}`

Server Script
`data.items = [];

var gr = new GlideRecord("sp_widget");
gr.orderBy('name');
gr.query();
while(gr.next()) {
	if ($sp.canReadRecord(gr)) {
		var hash = {};
		var have_content = 0;

		var fields = gr.getFields();
		if (fields != null) 
		{
			hash['sys_id'] = gr.getValue('sys_id');
			for (var i = 0; i < fields.size(); i++) {
				var glideElement = fields.get(i);
				var name ="";
				try {
					name = glideElement.getName();
				} catch (e) {}
				if (name == 'name') hash[name] = gr.getValue(name);
				if (name == 'id') hash[name] = gr.getValue(name);

				var res= {};
				if (name == 'template') {
					var template_text = gr.getValue(name);
					if (template_text != null) {
						var regExp = /\$\{(.*)\}/g;
						var matches = template_text.match(regExp);
						if (matches != null) {
							for (var j = 0; j < matches.length; j++)
							{
								var t = matches[j]; 
								var dirty= t.slice(2,t.length-1);
								var open_braces = 0;
								var cleaned ='';
								for (var x = 0, len = dirty.length; x < len; x++) {
										var c = dirty.charAt(x);
										if ( c == '{') open_braces++;
										if ( c == '}') open_braces--;
										if (open_braces < 0) break;
										cleaned = cleaned.concat(c);						 
									}
								res[j] = cleaned;
							}
							if (res != null) {
								hash[name] = res; 
								have_content = 1;
							}
						}
					}
				}
			}

			if (have_content == 1) data.items.push(hash);
		}
	}
}`

This widget is working fine.
Now I tried to enhance the scripts to be able to check if there is a translation existing, or not.
But I'm very new to AngularJS and maybe the JSON is not right structured. I'm not able to render my results in a proper way.
Note: You have to install other language plugins first to be able to see the other translations!

HTML Template
`<div class="panel panel-default">
    <div class="panel-heading">List of widgets including text to translate</div>
  	<div class="panel-body">
      <div ng-repeat="item in c.data.items">
          <h3><a ng-href="?id=widget_editor&sys_id={{item.sys_id}}">{{item.name}}</a></h3>
    		<ul><li ng-repeat="temp in item.template">{{temp}}
               <ul><li ng-repeat="ori in temp.original">{{ori}}</li></ul>      
               <ul><li ng-repeat="trans in temp.translation">{trans}}</li></ul>      
            </li></ul>      
      </div>     
    </div>
  <!-- <pre>{{data|json}}</pre> --!>
</div>
`  
Server Script

`data.items = [];

var gr = new GlideRecord("sp_widget");
gr.orderBy('name');
gr.query();
while(gr.next()) {
	if ($sp.canReadRecord(gr)) {
		var hash = {};
		var have_content = 0;

		var fields = gr.getFields();
		if (fields != null) 
		{
			hash['sys_id'] = gr.getValue('sys_id');
			for (var i = 0; i < fields.size(); i++) {
				var glideElement = fields.get(i);
				var name ="";
				try {
					name = glideElement.getName();
				} catch (e) {}
				if (name == 'name') hash[name] = gr.getValue(name);
				if (name == 'id') hash[name] = gr.getValue(name);

				var res= {};
				if (name == 'template') {
					var template_text = gr.getValue(name);
					if (template_text != null) {
						var regExp = /\$\{(.*)\}/g;
						var matches = template_text.match(regExp);
						if (matches != null) {
							for (var j = 0; j < matches.length; j++)
							{
								var t = matches[j]; 
								var dirty= t.slice(2,t.length-1);
								var open_braces = 0;
								var cleaned ='';
								for (var x = 0, len = dirty.length; x < len; x++) {
										var c = dirty.charAt(x);
										if ( c == '{') open_braces++;
										if ( c == '}') open_braces--;
										if (open_braces < 0) break;
										cleaned = cleaned.concat(c);						 
									}
								//res[j] = cleaned;
								have_content = 1;
								var sm = new GlideRecord("sys_ui_message");
								sm.orderBy('name');
								sm.query('key',cleaned);
								translations = {};
								var z=0;
								while(sm.next()) {
									if ($sp.canReadRecord(sm)) {
										var trans_hash = {};

										var fields = sm.getFields();
										if (fields != null) 
										{
											trans_hash['sys_id'] = sm.getValue('sys_id');
											for (var i = 0; i < fields.size(); i++) {
												var glideElement = fields.get(i);
												var name ="";
												try {
													name = glideElement.getName();
												} catch (e){}
												if (name == 'language') trans_hash[name] = sm.getValue(name);
												if (name == 'message') trans_hash[name] = sm.getValue(name);
												}
											}

											translations[z]=trans_hash;
											z++;
									}
								}
								res[j]=translations;
							}
							if (have_content > 0) {
								var templates = {};
								var original ={};
								original [0]=cleaned;
								templates ["original"]= original;
								templates ["translation"]= translations;
								hash['template'] = templates; 
								
							}
						}
					}
				}
			}

			if (have_content == 1) data.items.push(hash);
		}
	}
}`

Who can help me correcting this code?
Result should be:

Widget Name
  - translation text
    - language a: translation (link to https://platformname.service-now.com/nav_to.do?uri=sys_ui_message.do?sys_id=xxxxxxxxxxxxxx)
    - language b: translation (link)

....

Thanks,
Averell

**Comment by iamwill** [comment]
I'm doing some research but in the meantime you can turn on translation prefixes and service portal will show you where the message keys are in your widgets.

![screen shot 2016-06-30 at 8 11 40 am](https://cloud.githubusercontent.com/assets/179779/16493905/2cb7eb2c-3e9c-11e6-9a4d-2e0a22f07b52.png)

![screen shot 2016-06-30 at 8 11 04 am](https://cloud.githubusercontent.com/assets/179779/16493909/30d51964-3e9c-11e6-89fa-0a94e8109224.png)

**Comment by klima** [comment]
It's work pretty good, but have one problem. 
When i try show JSON variable from instance `(Additional options, JSON format)` translator not working. 
It look like this `${{{data.name}}}`. 
Do u have solution for this?

**Comment by yagoferrer** [comment]
@klima do it server-side.
options.name = gs.getMessage(options.name);

**Comment by patrickw14** [comment]
Link to the docs as well: https://github.com/service-portal/documentation/blob/master/documentation/widget_internationalization.md
