### ISSUE TITLE
access to $sp.getParameter('sys_id') from embedded widget.

### ISSUE THREAD

**Issue by sasukepatel** [service-portal/documentation#32]
i have made cart like widget and embedded it to Copy of "SC Catalog Item" widget. in my cart widget server script i'm trying to get sys_id of the page. im using $sp.getParameter('sys_id'). but it doesnt work.
it returns undefined/null.

Does $sp work on embedded widgets?

**Comment by deconroy** [comment]
Hi Rushit,

$sp.getParameter() does not currently work within embedded widgets. I am not sure if it is coming in a future patch or not.

What you can do to get these parameters in an embedded widget is to pass them in as either input, or options into the embedded widget. The recently updated [embedded widget](https://github.com/service-portal/documentation/blob/master/documentation/widget_embedded.md) documentation explains how to provide options or input to en embedded widget.

Hope this helps.

Dan
