### ISSUE TITLE
Returning ALL variables with $sp.getVariablesArray();

### ISSUE THREAD

**Issue by pflantzdog27** [service-portal/documentation#34]
Is it possible that this function takes some parameters?
I'm having a hard time understanding why it doesn't return ALL of the variables of a given catalog item.
As far as I can tell only the following keys are included in the array:
 -- display_value
 -- name
 -- id
 -- label
 -- type
 -- value

**Comment by CapaJC** [comment]
No parameters for that method. And that's correct, those are the keys in that Array. What else, specifically,  are you expecting to see?

Some variable types are ignored there, like Break, Macro, UI Page, Container vars, HTML...basically types that do not accept user input.

Sounds like we should better document the purpose of that method, maybe?

**Comment by pflantzdog27** [comment]
I was hoping Category would be included in that array too. 
There are variables that we'd like to display when the user fills out a request but then not necessarily display in their ticket. We could use that Category field for logic purposes.

**Comment by CapaJC** [comment]
Well wouldja' look at that. Variables have a Category. I've been here 10 years and didn't know that.

It also looks like we don't populate that field in any of the 989 Variables my default instance has, so I guess I'm not surprised I didn't know about it.

**Comment by pflantzdog27** [comment]
Ha! Yea - I scoured the options to find a column to hijack -- wouldn't have known myself otherwise.

**Comment by michelek87** [comment]
So Category field on the Variables is just a thing... doesn't get used anywhere in the system?

Also, I was playing around to see what variables show and which ones don't in the "Options" section of the RITM and Approval record on the Portal.

What I found:
True / False variables:
If you submit the request in ITIL view, the variables with false value show in the portal
If you submit the request in the Portal view, the variables with false value do NOT show in the portal

String fields:
If empty, they do not show up in the portal (doesn't matter if you submit on ITIL or Portal side)

Visible on Summaries does nothing in the portal

Such fun learning a new tool with undocumented features ;P

**Comment by CapaJC** [comment]
The code that $sp.getVariablesArray calls into currently omits null/empty values (including Boolean false). Interesting idea, but I think not what people expect.

For Istanbul and potentially a later Helsinki patch, that method will take an optional Boolean parameter that, if true, will include nil responses. It will most likely make its way to being a widget option that can be set on a per-widget-instance basis, since OOB widgets can't be modified to add/remove this parameter.

**Comment by michelek87** [comment]
Sounds good.  I did some testing and if you submit a request within the portal the false fields and values don't appear in the options summary in the portal.   If you submit the same request from the itil side the false fields and values will show in the options summary on the portal.   This was tested in my clean DEV instance on Helsinki
