### ISSUE TITLE
sp-message-dialog localization translation

### ISSUE THREAD

**Issue by Snow-Averell** [service-portal/documentation#35]
The Attachment Ticket Widget contains the following code
`    
<sp-message-dialog name="delete_attachment" 
                       title="Delete Attachment" 
                       message="Are you sure?" 
                       ok="OK" 
                       cancel="Cancel" 
                       dialog-class="delete-dialog"/>
  </div>
`
I think the dialog will not translate. Should ootb widgets not be fully translated?

**Comment by CapaJC** [comment]
They should. It's a bug. I'll log a PRB.

**Comment by patrickw14** [comment]
Working on this for release in a patch. Thanks!
