### ISSUE TITLE
Accordion with Bootstrap collapse.js

### ISSUE THREAD

**Issue by Hages** [service-portal/documentation#41]
Hi,
I've implemented an accordion in a widget for a FAQ page, but it is not behaving as expected.  This errant behaviour occurs even when I copy the example code from the Bootstrap example - http://getbootstrap.com/javascript/#collapse.
When clicking on the accordion headers, depending on the state of the accordion, sometimes it bhaves correctly.  Other times, it opens all items incorrectly.
Thanks,
Craig.

**Comment by patrickw14** [comment]
Looks like that functionality requires the transitions bootstrap plugin, according to those docs. Have you tried pulling that in? We have documentation on third party dependencies that you can reference.

Not sure how else I can help without something more concrete to look at. Try pulling in the plugin above, and if that doesn't work, send me an email with your instance name and login credentials and I'll see if I can provide any advice.

patrick.wilson@servicenow.com

**Comment by Hages** [comment]
Thanks for your help Patrick, I implemented the Bootstrap UI version of the accordion and it works well.
