### ISSUE TITLE
Localization select box on Service Portal

### ISSUE THREAD

**Issue by klima** [service-portal/documentation#43]
Hi, 
i have problem with language select box. 
Old version is looking like this:
`        <SELECT id="language_select" name="language_select" onchange="ls.change();">
            <option value="">${gs.getMessage("Loading...")}</option>
        </SELECT>`

But now obj ls generate errors. 
How it should look on angular?

**Comment by patrickw14** [comment]
Can you be more specific with the error that you're seeing? I suspect it's because of that ls.change() not actually existing in your widget, but it's hard to say without more context.

**Comment by klima** [comment]
Hi,
Yes, ls change() is not defined and object LanguageSelect is not defined too.

I need a function that works as a ls.change() - change languge for logged user. 
Like this:
<img width="494" alt="zrzut ekranu 2016-07-13 o 10 45 17" src="https://cloud.githubusercontent.com/assets/6649636/16797247/ed668302-48e6-11e6-8802-564de600c013.png">

**Comment by frankschuster** [comment]
That could just be a little widget with a Bootstrap select type. You would pull all active languages on the server (with some GlideRecord magic) and then have your select type display those languages (with ng-options).

You would also need to write a little script that sets the chosen language as the user preference for the current logged in user.

**Comment by CapaJC** [comment]
I think there is an spUtil function that sets a user preference… I'll have to look it up. 

--J

On Jul 13, 2016, at 3:34 AM, Frank Schuster <notifications@github.com> wrote:

That could just be a little widget with a Bootstrap select type. You would pull all active languages on the server (with some GlideRecord magic) and then have your select type display those languages (with ng-options).

You would also need to write a little script that sets the chosen language as the user preference for the current logged in user.

**Comment by CapaJC** [comment]
I was wrong about spUtil, it's its own service *spPreference*. So add spPreference to the widget controller's dependencies (e.g., function ($scope, spUtil, spPreference)), and use it to set a preference like:

spPreference.set("preference_name", "preference value");

**Comment by frankschuster** [comment]
Sweet, thanks! Scratch the user preference script then :)

**Comment by patrickw14** [comment]
Excellent - that should be enough to get started. @klima, if you find any SP issues while you're building that language picker widget, feel free to create another issue. I'll close this out for now.
