### ISSUE TITLE
List collector with commas in display field

### ISSUE THREAD

**Issue by zzjasonzz** [service-portal/documentation#44]
If a list collector has a display field with commas then it's not displaying properly on the screen.  So we have lastname, firstname.  Could it be some issue with get value / set value using comma delimited lists of values?

**Comment by iamwill** [comment]
Good catch, looks like we are splitting values and display values on comma. We'll get it fixed.

**Comment by iamwill** [comment]
If that is a calculated field, can you try using &comma; as the separator?

**Comment by zzjasonzz** [comment]
Do you know what type of fix will be applied?  A different separator value?

**Comment by iamwill** [comment]
Not sure. We probably just need to convert the display values into html entities before the component parses the list.

**Comment by zzjasonzz** [comment]
Ok, we are also using getValue and setValue to work with list collectors in SP.  to set multiple values we have to use a comma delimited string for values and display values.  I tried using an array but it would only work with a delimited string

**Comment by zzjasonzz** [comment]
We will try changing to a different delimiter as a workaround for now.
