### ISSUE TITLE
Language Attribute on HTML

### ISSUE THREAD

**Issue by arthur-cheung** [service-portal/documentation#45]
Hi,

We have a requirement Web Content Accessibility Guidelines. One of these is to specify the language on the HTML document (i.e. we just need the attribute `language="en"` on the HTML element).

We failed this test with the details below. Is there any property / configuration on the portal we can set to satisfy this?

Thanks in advance.

Cheers,
Arthur

## Test Results

3.1 Readable: Make text content readable and understandable.

Success Criteria 3.1.1 Language of Page (A)

Check 48: Document language not identified.
Repair: For HTML documents add the lang attribute and a valid ISO-639-1 two letter language code to the opening HTML element. For XHTML documents add both the lang and xmllang attributes with a valid ISO-639-1 two letter language code to the opening HTML element.
Error Line 1, Column 1:
<html ng-init="portal_id = 'a6e5ea330fdc2a0002744cace1050ea1'" style="height: 100%;" ng-app="sn.$sp" ...
Check 49: Document has invalid language code.
Repair: Add a valid 2 letter or 3 letter language code as defined in the ISO 639 specification to the HTML 'lang' attribute. For XHTML, both 'lang' and 'xml:lang' must be set.
Error Line 1, Column 1:
<html ng-init="portal_id = 'a6e5ea330fdc2a0002744cace1050ea1'" style="height: 100%;" ng-app="sn.$sp" ...

>

**Comment by yagoferrer** [comment]
Hello, I created a PRB for this and it will get fixed in the next patch.
