### ISSUE TITLE
Document how to handle business rules that abort the server side widget script inserts.

### ISSUE THREAD

**Issue by dynamicdan** [service-portal/documentation#48]
Currently we may insert GlideRecords on the server but it's possible that a business rule aborts the insert. How can the server side script in a widget "catch" this?

Is any communication between a business rule and a widget possible?

**Comment by jneale** [comment]
I use getLastErrorMessage() and isActionAborted() to check for this. I have a commit(gr) function that does all these checks for me automatically on any GlideRecord - so I don't ever have to call update(). (Side note - calling update will do an insert if it's a new record).

**Comment by nathanfirth** [comment]
@jneale You're so smart :)

**Comment by patrickw14** [comment]
There aren't any SP or Widget-specific ways to handle this -- just like @jneale suggested, you can handle those things the same way you handle it in any other Script Include in the platform. 

So, using the technique that @jneale mentioned, you can pull your GlideRecord update/insert call into your own Script Include function which returns an error state if there is a failure of some sort, which you can then react to from within your widget's server script.
