### ISSUE TITLE
Reference fields and sn-record-picker with multiple columns

### ISSUE THREAD

**Issue by nathanfirth** [service-portal/documentation#49]
I have two issues we've found with reference fields in Service Portal. The first is that when displaying multiple columns in a reference field (select2), it correctly generates the columns and width's, but the class the sets the columns to inline-block is missing and thus they all stack on top of each other making it very hard to use. See below:
![reference](https://cloud.githubusercontent.com/assets/805398/16810960/1406d7ca-48db-11e6-8f7c-72270c04fbf2.jpg)

The other issue is when setting the variables of on a catalog item, and setting properties to search the multiple columns. Setting this property works in the platform UI but fails to search the additional columns in Service Portal.
![screen shot 2016-07-13 at 9 23 41 am](https://cloud.githubusercontent.com/assets/805398/16811153/ed3307f8-48db-11e6-96bd-edd06113f715.png)

I'm guessing these issues exist in the form widget, catalog variables, and sn-record-picker directive, but did not test everywhere.

**Comment by zzjasonzz** [comment]
We've also noticed the behavior of each field in a select is getting its own line.  That would be nice to have fixed.  

Patch 2 has fixed our issue with searching multiple columns in a reference field.

**Comment by nathanfirth** [comment]
@zzjasonzz The quick work around for the multiple columns is just add the class as shown above in your theme css.

**Comment by zzjasonzz** [comment]
Yeah, I'm going to make that change, thanks!

**Comment by zzjasonzz** [comment]
I tried that CSS fix and it did make the columns display horizontal.  Now the data in some of the drop down columns are overlapping each other.  The width of the expanded drop down is being limited to the same width as the select control whereas he platform will allow the expanded list to be wider.

**Comment by patrickw14** [comment]
Just confirming that the variable attribute fix did indeed make it into P2 (thanks @zzjasonzz!)

**Comment by zzjasonzz** [comment]
Yeah, that was in there and working now.
