### ISSUE TITLE
Order Guides and Variable Sets

### ISSUE THREAD

**Issue by xxJimxx** [service-portal/documentation#51]
Hello,

g_service_catalog.isOrderGuide() gave us a great start to identifying if we are in an order guide or not but I have some variable sets that are used in the order guide as well as the catalog items with values being cascaded down to the items.  These variable sets also have onChange scripts but when in the order guide I only want some of these script methods to run at the item level.  (If isGuide and inItem I need to prevent some script methods.)  Any ideas to accomplish what we need here?

Thanks, Jim

**Comment by xxJimxx** [comment]
Figured out a hack to use for now.  Found that the parent order guide page does not have an associated table like the included items...
	//if tablename is present then item otherwise top level guide
	if ( ! ( g_service_catalog.isOrderGuide() && g_form.getTableName() ) ) {
              // this is top form of order guide or stand alone catalog item
	}

**Comment by iamwill** [comment]
Yeah let's leave it at getTableName() for now. Good idea.
