### ISSUE TITLE
Clone Requests

### ISSUE THREAD

**Issue by diegobrf** [service-portal/documentation#52]
Guys, one of the main goals on our Service Now implementation is to enable bulk requests for our end users. Multiple requests for multiple beneficiaries. 

I know it can be acomplished with a few limitations on the backend, but what about the Service Portal?

**Comment by patrickw14** [comment]
I don't know how much luck you will have using the out-of-box widgets (hard to know without a lot more detail about exactly what you folks are doing), but creating your own widgets to do whatever you'd like them to do would be fairly straightforward for any developer that is familiar with HTML and Javascript. To get started with that process, these docs are a great place to start.
