### ISSUE TITLE
Service Catalog Variable of type Multiple Choice using Across vs. Down

### ISSUE THREAD

**Issue by toddstocking** [service-portal/documentation#55]
I noticed with a Service Catalog Variable that is of type Multiple Choice that the "Across vs Down" option does not appear to be used when displaying catalog items through the Service Portal.  They appear to default to "Down" in the layout.  Is this expected behavior?

**Comment by CapaJC** [comment]
I suppose it's not *unexpected* behavior, looking at the code. That variable type currently renders just the one way in Service Portal.

**Comment by toddstocking** [comment]
Ok thanks @CapaJC

**Comment by patrickw14** [comment]
If there were any other questions here, please feel free to open up this issue again
