### ISSUE TITLE
Widget Dependency being loaded and affecting the entire portal?

### ISSUE THREAD

**Issue by toddstocking** [service-portal/documentation#56]
If I create a widget dependency and select "Include on Page Load" it loads correctly and I see the external Angular and CSS load.  However, it is loading on all Service Portal pages and widgets and not just the specific widget that I defined the dependency for.

**Comment by yagoferrer** [comment]
That's correct. If you select include "on page load", we need to display a list of portals to select what portal you would like to load the module. Are you experiencing any problems when lazy loading the directive? I would like to know more why are you using this option.

**Comment by yagoferrer** [comment]
This will get fixed in patch 4
