### ISSUE TITLE
Service Catalog Page not considering "Container" variables.

### ISSUE THREAD

**Issue by dpm566** [service-portal/documentation#58]
Hi,

We are building a service portal which will use lot of service catalog. 
The customers are used to the flexible layouts(1/2/3 columns) in the service catalog which is currently not working using the widget "SC Catalog Item".
The widget seems to be ignoring the container variables.

I saw few directives which make up this view but are not accessible in the instance.
```
<sp-cat-item item="::data.sc_cat_item" />

> <sp-model form-model="::data.sc_cat_item" mandatory="mandatory"></sp-model>
```

Can you please suggest a possible solution to this problem.

Regards,
Durga

**Comment by christophercox398** [comment]
If you are hiding variables in your container it hides the entire container right?  I believe there is an open problem for this PRB691553  scheduled for patch 4.

**Comment by iamwill** [comment]
Service Portal only supports split layouts currently. If you want to manually recreate the layout you can clone the sc_cat_item widget and play with formModel._sections to create different form layouts.
