### ISSUE TITLE
sn-record-picker directive

### ISSUE THREAD

**Issue by jbwilmoth** [service-portal/documentation#59]
How do you add filters to the sn-record-picker based on another sn-record-picker field?

Do you have a list of everything available with the sn-record-picker directive?

Also, when not using sn-record-picker and loading a form to try and work around not being able to add filters to the sn-record-picker. After grabbing a form value to populate data in another widget – by calling this.server.update() – when the server updates, it clears the form and just displays a message that says "No Elements to display". Is there a way to update the server without the form clearing and displaying this message?

Thank you,
Joe

**Comment by iamwill** [comment]
Hello. sn-record-picker has the following scope attributes:

scope: {
			field: '=',				// The field object, like all other form elements have.
			table: '=',				// The table to search.
			defaultQuery: '=?',		// A base query that provides further result filtering. Like a reference qualifier.
			searchFields: '=?', 	// Comma separated fields to search
			valueField: '=?', 		// Field to use for field.value. Default is sys_id.
			displayField: '=?',		// Field to use for field.displayValue. Default is determined by getDisplayValue
			displayFields: '=?', 	// Additional fields to show in result row.
			pageSize: '=?',
			onChange: '&',
			snDisabled: '=',
			multiple: '=?',
			options: '=?',
			placeholder: '@'
		}

You should be able to use "defaultQuery" and the onChange binding to do what you want.

**Comment by mdshislam** [comment]
Hi @iamwill 

I want to allow user to select multiple records through a sn-record-picker directive. Below is the code i have written for the same:-

HTML:-
<div class="filterband">
  <div class="filter-liner container">
   
    <div class="panel panel-default">
    <div class="col-sm-2">
        Select Choice
    </div>
</div>
<div class="col-sm-7">
    <sn-record-picker field="watch_list" table="'u_c_choice_definition'" display-field="'u_choice_name'" value-field="'sys_id'" default-query="'u_choice!=Retired'" search-fields="'u_choice_name'" multiple="true"></sn-record-picker>  
    </div>
  </div>
</div>
 
 
Client Script:-
$scope.watch_list = { 
        displayValue: $scope.data.u_choice_name,
        value: $scope.data.sys_id,
        name: 'watch_list' 
     }; 
  $scope.$on("field.change", function(evt, parms) {      
    if (parms.field.name == 'u_choice_name'){
        $scope.data.u_choice_name = parms.newValue;
        $scope.server.update();
    }
});
 
Server Script:- No Server Script

Users are not able to anyway select anyrecord in the field.

Can you help?

Thanks,
Shahid

**Comment by iamwill** [comment]
Do you get any errors in the javascript console? If you remove the multiple attribute does it work ok?

**Comment by mdshislam** [comment]
Hi @iamwill 

Yes when i remove the "multiple" attribute it works ok.

The error which comes up says:-

Uncaught TypeError: Cannot read property 'split' of undefined
    at HTMLInputElement.onSelecting (VM5313 js_includes_sp.jsx?v=11-08-2016_1607&lp=Mon_Dec_12_10_26_59_PST_2016&c=5_52:28104)
    at HTMLInputElement.dispatch (VM5313 js_includes_sp.jsx?v=11-08-2016_1607&lp=Mon_Dec_12_10_26_59_PST_2016&c=5_52:2898)
    at HTMLInputElement.elemData.handle (VM5313 js_includes_sp.jsx?v=11-08-2016_1607&lp=Mon_Dec_12_10_26_59_PST_2016&c=5_52:2689)
    at Object.trigger (VM5313 js_includes_sp.jsx?v=11-08-2016_1607&lp=Mon_Dec_12_10_26_59_PST_2016&c=5_52:2846)
    at HTMLInputElement.<anonymous> (VM5313 js_includes_sp.jsx?v=11-08-2016_1607&lp=Mon_Dec_12_10_26_59_PST_2016&c=5_52:3243)
    at Function.each (VM5313 js_includes_sp.jsx?v=11-08-2016_1607&lp=Mon_Dec_12_10_26_59_PST_2016&c=5_52:215)
    at jQuery.fn.init.each (VM5313 js_includes_sp.jsx?v=11-08-2016_1607&lp=Mon_Dec_12_10_26_59_PST_2016&c=5_52:59)
    at jQuery.fn.init.trigger (VM5313 js_includes_sp.jsx?v=11-08-2016_1607&lp=Mon_Dec_12_10_26_59_PST_2016&c=5_52:3242)
    at constructor.triggerSelect (VM5313 js_includes_sp.jsx?v=11-08-2016_1607&lp=Mon_Dec_12_10_26_59_PST_2016&c=5_52:51543)
    at constructor.onSelect (VM5313 js_includes_sp.jsx?v=11-08-2016_1607&lp=Mon_Dec_12_10_26_59_PST_2016&c=5_52:52880)

Any idea on what is the issue?

Thanks,
Shahid

**Comment by iamwill** [comment]
What release/version are you running? This might have been fixed somewhat recently.

**Comment by mdshislam** [comment]
Helsinki is the version. Can you tell me way how i can fix it or how i can build a custom multiselect reference field? Any piece of code would help?

**Comment by ntrval** [comment]
What he means by may have been fixed and what version is check the
patch/hotfix version you are on and then check changelogs for recent fix.
"May have been fixed" implies that he was unable to reproduce your issue.

**Comment by mdshislam** [comment]
Hi @iamwill ,

glide-helsinki-03-16-2016__patch7-11-02-2016_11-08-2016_1607

this is it. Any help?

**Comment by iamwill** [comment]
Looks like you found a bug - thank you. I just fixed it.

In the meantime make sure your field $scope.watch_list needs two properties. Do this in your init: $scope.watch_list.value ="";
$scope.watch_list.displayValue = "";

Then it should work.

The bug fix should release with Jakarta.

FYI, we don't support these directives for use outside of our own form widget. These are for internal use only.
