### ISSUE TITLE
Mobile App to Service Portal

### ISSUE THREAD

**Issue by jonathanjacob** [service-portal/documentation#60]
Does Service Portal/ The mobile app have some bridge or connection? 

For example: I have a Service Portal Page accessible via the Navigation in the ServiceNow Mobile App. I want to be able to navigate from the Service Portal embedded UI to the Mobile Apps view of a form. 

I see that "cabrillo" is used to bridge native/sp, I don't see it documented. 

I tried:
`cabrillo.navigation.goto();`

this looks like it doubles up the UI rather than navigating within the app.
![image](https://cloud.githubusercontent.com/assets/3483681/17006769/4bc41a52-4eb1-11e6-9b62-4ae460d9a94e.png)

**Comment by fdn** [comment]
The mobile app will listen for webview changes and if the webview change is to a record/list/other supported resource, it should intercept that request. You can use desktop URLs or you can use mobile URLs. If you want to ensure it works on Desktop and mobile, you should use Desktop URLs. 

For example:
```html
<a href="incident.do?sysId=-1">Desktop URL to create an incident</a>
<a href="$m.do#/form/incident/a9e30c7dc61122760116894de7bcc7bd">Mobile URL to go to a specific incident</a>
```

In short, you don't need cabrillo to handle the functionality you need. Cabrillo will just complicate matters. (Also cabrillo isn't a stable/public API.)

Good luck!

**Comment by jonathanjacob** [comment]
Great, guess that was too easy and I overcomplicated it! 
Thanks for the help @fdn
