### ISSUE TITLE
How to deploy a new portal/update sets

### ISSUE THREAD

**Issue by Cayley** [service-portal/documentation#65]
Hi 
I'm in the process of migrating our newly developed service portal from Dev to UAT instances.

The portal record itself will not get included in update sets (even when forced).
I exported the portal as an individual record and this partly worked... but now i'm missing pages.

Is there some guidance on how to deploy service portals? I feel like I've missed an important step.

Thanks
Cayley

**Comment by enojardi** [comment]
Hi Cayley, which version of Helsinki are you running, I just tested this quickly in Helsinki Patch 2 and (as expected) it was captured in an update set as normal. 

In terms of the deployment question: Update sets and/or Team development is your answer. There is some limited support for scoped applications (e.g. if you're building a SPA) so you can publish the portal as part of an app and leverage dev tools like Studio and Source Control (however you won't be able to create the application files directly in there).

**Comment by Cayley** [comment]
Turns out it was an update set issue within our environment. Thanks for the help.
