### ISSUE TITLE
Service Portal Asynchronous Server Script

### ISSUE THREAD

**Issue by klima** [service-portal/documentation#68]
Hi,
is possible to run asynchronous server script on service portal? 
`$sp.getCatalogItem(data.sys_id);`

We have about 50 items attached to the order guide. Now what happens is they all get loaded each time we open the link to the service portal. It currently takes about 10 seconds or more, and unfortunately this happens each time we refresh the service portal.

**Comment by CapaJC** [comment]
You could probably do something with the "input" object. If it doesn't exist, then do nothing. Then in the client controller, do your asynchronous bit with a round trip. 

I'm pretty sure we have at least one example of this out of box, but I don't have access to the code right now. 

--J


On Jul 28, 2016, at 12:35 AM, klima <notifications@github.com> wrote:

Hi,
is possible to run asynchronous server script on service portal? 
$sp.getCatalogItem(data.sys_id);

We have about 50 items attached to the order guide. Now what happens is they all get loaded each time we open the link to the service portal. It currently takes about 10 seconds or more, and unfortunately this happens each time we refresh the service portal.

**Comment by klima** [comment]
Hi,

can you elaborate a bit on this "input" object - what do you mean exactly by that? How can we check if it exists or not? Do you mean the object containing all request items data? The issue is, all this seems to be loaded at the beginning, it does not matter if we add the item to cart or not.

Many thanks!

**Comment by frankschuster** [comment]
input is an object that only contains data when the client calls c.server.update(), thus onLoad of the server script that object will be undefined. Simply wrap an if(input) around your piece of server code that you want to prevent from loading in the beginning.

Also see [https://github.com/service-portal/documentation/blob/master/documentation/widget_server_script.md](Widget Server Script)

**Comment by patrickw14** [comment]
^ Great answer, @frankschuster ! Thank you
