### ISSUE TITLE
Widget Description/usage Documentation

### ISSUE THREAD

**Issue by dynamicdan** [service-portal/documentation#69]
Most widgets are not using the description field. Is there any reference to all SN provided widgets and their uses? Perhaps with example use cases? 

It would also be good to split the "utility" like widgets that are either for dev support or only work in conjunction with other certain widgets.

Currently I have 3 from 105 widgets with the description field filled in.

**Comment by omidborjianNow** [comment]
Thanks for your input. We're working on a showcase for our widgets with screenshots, categories and etc. Will link it to this documentation once it's done.
