### ISSUE TITLE
Document List usage

### ISSUE THREAD

**Issue by dynamicdan** [service-portal/documentation#70]
Currently there are ~4 list widgets. The have varying level of support and don't support advanced usage. ie, it took me a while to find a widget that supported the "view" param and this was via URL (not best option).

Also document specifics around list views. Eg, how to use a list with a custom view. Also, which widgets support A) displaying a list view and B) carrying over a view on click through to the form. The widget options and script always say "view" but this is ambiguous.

**Include list/view limitations...**
I also found an issue that dot walked elements that are shown in lists in the native SN UI don't work in the data tables widgets. Eg. short_description, number, u_meeting_item, u_meeting_item.date (failed in SP).

**Comment by patrickw14** [comment]
We're working on more in-depth documentation of all the core Service Portal out-of-box widgets which will hopefully solve some of these concerns. In that documentation, we will be sure to address these points for the List widget. Much appreciated!
