### ISSUE TITLE
Can't delete data from dropdown

### ISSUE THREAD

**Issue by dynamicdan** [service-portal/documentation#71]
Strange issue but right now I if I choose a table for a widget (any) then I can't clear it.
Even if I open it in platform view (/sp_instance_table.do) I can't remove the value in the table field. Is this a known issue??

Only way would be for me to delete the widget instance and re-create it. Not ideal.
(glide-helsinki-03-16-2016__patch2-06-15-2016)

**Comment by CapaJC** [comment]
In platform view, the option at the top of the table list is “—None –“, which worked for me.

 

When editing widget options in the portal, it doesn’t look like we provide that option. Sounds like a bug to me.

 

--J

**Comment by patrickw14** [comment]
Bug acknowledged - we'll look into this, thanks for the heads-up!
