### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by mak42** [service-portal/documentation#72]
Is there a possibility to change routing of service portal? We have two Homepages and based on Group Membership User should be redirected to one of the two pages.

**Comment by patrickw14** [comment]
Two things you can do here:

1. Use SPEntryPage to route users to one of your homepages when they login or when they navigate to your instance. Docs on this process can be found here: https://github.com/service-portal/documentation/blob/master/documentation/sso_configuration.md

2. You can have a widget on those two pages that checks the user's group memberships and routes them to a different page using the Angular construct $location (very well documented on their site).

I recommend the first option, but you can always script it in a widget if you choose to.
