### ISSUE TITLE
Document $emit in DataTables widget

### ISSUE THREAD

**Issue by dynamicdan** [service-portal/documentation#73]
I'd like to add a link to the datatable widget to open the record/row but I only found an option via the "go" function. How do I hook into the **$emit** object? What is this object?

Reference:
```
$scope.go = function(table, item) {
		var parms = {};
		parms.table = table;
		parms.sys_id = item.sys_id;
		parms.record = item;
		$scope.ignoreLocationChange = true;
		for (var x in c.data.list) {
			c.data.list[x].selected = false;
		}
		item.selected = true;
		$scope.$emit(eventNames.click, parms);
	};
```

**Comment by patrickw14** [comment]
$emit is an AngularJS construct, you can read more about eventing in Angular here: https://toddmotto.com/all-about-angulars-emit-broadcast-on-publish-subscribing/

**Comment by dynamicdan** [comment]
I added the event listener function but I don't get the same parms as sent in "go".
````
var eventNames = {
	click: 'data_table.click',
	setFilter: 'data_table.setFilter',
	setKeywords: 'data_table.setKeywords'
};
	
$scope.$on(eventNames.click, function(parms) { 
	console.log(parms);
});
````

Instead I get:

````
currentScope: null,
defaultPrevented: false
name:"data_table.click"
preventDefault:()
stopPropagation:()
targetScope:Scope
__proto__:Object
````

No `parms.sys_id` option for me :-(

**Comment by sasukepatel** [comment]
i have been there. first parameter is event description and second parameter will be your passed data.
it will be $scope.$on(eventname,function(eventdesc, data){
});
