### ISSUE TITLE
How to display Live Feed in Service Portal

### ISSUE THREAD

**Issue by peter-repan** [service-portal/documentation#75]
Hi, 
is there any out of the box widget for displaying Live Feed in Service Portal? 
Or is the only option to create a widget with iframe "live_feed_launcher.do" ?

**Comment by patrickw14** [comment]
No out-of-box widgets to handle that, though I suspect that somebody will eventually build some widgets to do that (maybe a partner or someone in the developer community?). We don't have any plans to build that as of today.

One option is certainly to just put it in an iframe as you say, or if you were interested in devoting more developer resources to the problem, you could use the Live Feed API and the Table API to build a custom suite of widgets to do whatever you'd like, and you would get a much better outcome. All depends on what you're looking for, of course.

**Comment by jcfourie** [comment]
Patrick you talk about the Live Feed API? Could you point me to some documentation for that? I would be really interested to look at it
