### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by jonathanjacob** [service-portal/documentation#76]
Hi,

With the old CMS the platform provided a ${CMS_URI} convenience function in email notifications to properly link to the correct detail page for the record. Does Service Portal have a similar function? I am working on a mail script to do so otherwise, but I just wanted to see if this existed...

**Comment by CapaJC** [comment]
Service Portal has no such concept, as yet.

**Comment by jonathanjacob** [comment]
Thanks for confirming this!
