### ISSUE TITLE
"None" option missing from variable in Record Producer

### ISSUE THREAD

**Issue by nathanfirth** [service-portal/documentation#78]
In the platform UI I am seeing the "none" option but in Service Portal it only gives you the option to select a record.

Is there a work around for this, or has this been fixed in a patch?

![screen shot 2016-08-03 at 11 25 42 am](https://cloud.githubusercontent.com/assets/805398/17377145/6f0ac350-596d-11e6-93ba-0d6c5afc1cf2.png)

**Comment by CapaJC** [comment]
I fixed an issue just Monday w/ a missing "-- None --" choice for dependent choice list fields that might be related. Targeted for Helsinki Patch 4.

What's your variable setup there? Is that a Select Box variable dependent on another one?

**Comment by nathanfirth** [comment]
Here are the settings for the variable. Looks like it's the same issue you fixed.
![screen shot 2016-08-03 at 1 19 28 pm](https://cloud.githubusercontent.com/assets/805398/17380732/6b55caba-597d-11e6-91ab-bfa5bda78574.png)

**Comment by patrickw14** [comment]
If this is all sorted,  I'll close this out! Cheers Nathan
