### ISSUE TITLE
List Collector Meta Data - in Service Portal

### ISSUE THREAD

**Issue by lars-oliver** [service-portal/documentation#79]
Currently in the main UI for List collectors (slushbuckets) there is meta data underneath the list collector that is displayed based on reference field. Does similar functionality exist for Service Portal? We cannot even seem to push using ref-ac columns as attributes (what is normally done for reference fields to show data side by side)

For reference: http://wiki.servicenow.com/index.php?title=Slushbucket#gsc.tab=0
1.2.1 Information Fields for Available Items
Information fields for the highlighted available item appear beneath some slushbuckets. The information fields are the same as the reference lookup for a reference field on a form. To modify which fields appear, configure the reference lookup list.

**Comment by zzjasonzz** [comment]
Multiple columns are displaying on separate lines instead of side by side in patch 2 for us.  Make sure the default list view has the columns in it that you want to display in the list collector in service portal.  After we updated our default columns for the list view they started showing up in the list collector.

**Comment by lars-oliver** [comment]
@zzjasonzz, would you mind sending a snapshot of how this looks?

**Comment by zzjasonzz** [comment]
![image](https://cloud.githubusercontent.com/assets/20165428/17490624/ada0e02e-5d71-11e6-8614-edd3021d5362.png)

**Comment by zzjasonzz** [comment]
That screenshot is actually two entries in the reference table.  Each field is displaying on a separate line instead of hoizontally.  The screenshot is actually a reference field though, not a list collector.

**Comment by lars-oliver** [comment]
That looks like two separate records in the referenced table. So what we are looking to push side by side is two fields from the record. For example for a sys_user record, Full name and User ID

**Comment by lars-oliver** [comment]
similar to using ref_ac_columns on a reference record, we would want to see this for the list collector (in service portal view)

**Comment by zzjasonzz** [comment]
We haven't done that with a List Collector yet.  Right now we are just displaying a single field in the list collectors which is always the default display field.

**Comment by lars-oliver** [comment]
Okay, because list collectors in the main UI had the following functionality: 

![image](https://cloud.githubusercontent.com/assets/20848805/17490995/d3fd18d2-5d62-11e6-9554-81f6db7d2ccc.png)

**Comment by zzjasonzz** [comment]
As a site note...you can't have a display value in the list collector if it has a comma in the display value.  The control wasn't handling comma's in the display value in patch 2.

I suspect that the field value would have the same issue but we haven't had any comma's in field values yet, only display values.

**Comment by patrickw14** [comment]
Closed for inactivity - this is an old issue, if there is still some question here, please repost!
