### ISSUE TITLE
Switching between portals

### ISSUE THREAD

**Issue by lperutka** [service-portal/documentation#84]
How can I switch from one portal to another in Menu item?
If I use URL with the full address (https://xxx.service-now.com/sp2) then navigation bar is showing correct URL in the browser but the portal remains (new portal is not loaded). 

It is possible to do it by new page with widget which do the redirect but nicer solution is welcome.
Thanks
Lukas

**Comment by michaelmcalister** [comment]
Nathan Firth has a great post about how to switch portals here: http://serviceportal.io/navigating-multiple-service-portals.

**Comment by iamwill** [comment]
This bug has been fixed and will be available in a forthcoming Helsinki Patch.
