### ISSUE TITLE
getSCRecord()

### ISSUE THREAD

**Issue by t1mb0b** [service-portal/documentation#87]
I don't see this function in the list on the Server Script API page. 

I am trying to modify the search function in SP to include results for Content Items. I can add that table to the sp_search_group list, but that does not allow me to modify the <a> tag to the item URL as opposed to the item page. The 'Search Page' widget used the function:

`var sc = $sp.getSCRecord();`

Cheers,

Tim

**Comment by patrickw14** [comment]
The search page widget should be returning results from the sc_cat_item_content table - is it not in your instance?

**Comment by CapaJC** [comment]
Support for Content Items was only added in a recent patch. 3 or 4, I believe. 

--J

On Sep 13, 2016, at 9:25 AM, Patrick Wilson <notifications@github.com> wrote:

The search page widget should be returning results from the sc_cat_item_content table - is it not in your instance?

**Comment by t1mb0b** [comment]
I modified the query to use the standard GlideRecord method. This was pre- patch 4.

**Comment by patrickw14** [comment]
Oh, I see. My mistake. We'll write some docs on getSCRecord, to at least explain what it's doing.

**Comment by t1mb0b** [comment]
No worries, thanks Patrick!
