### ISSUE TITLE
Load Times

### ISSUE THREAD

**Issue by xxJimxx** [service-portal/documentation#88]
The javascript file appears to be quite heavy with load times in the neighborhood of 3.5 to 4 seconds when not cached.  Is there any plan to minify this script to reduce load times?

/scripts/js_includes_sp.jsx?v=06-30-2016_1135&lp=Mon_Aug_15_06_47_44_PDT_2016&c=3_114

**Comment by patrickw14** [comment]
That DOES seems like a very long time. We likely won't be removing any content from that file, but we will look into minification. No concrete plans yet. Thank you for the feedback!
