### ISSUE TITLE
Max Length for Variables

### ISSUE THREAD

**Issue by jonathanjacob** [service-portal/documentation#90]
I am using a "Wide Single Line Text" variable and service portal is setting the maxlength="40". In the legacy catalog view, you can enter 40+ characters.
It does not seem to be respecting the variable attribute "max_length" either.

http://wiki.servicenow.com/index.php?title=Variable_Types#Wide_Single_Line_Text

It also seems to be reported by another person on the community:
https://community.servicenow.com/thread/233878

**Comment by CapaJC** [comment]
What version? I'm sure this was fixed in patch 2 (maybe 3)

**Comment by CapaJC** [comment]
I was wrong. This sounds like PRB691597, fixed in Helsinki Patch 4

**Comment by jonathanjacob** [comment]
This is patch 2.
