### ISSUE TITLE
Roles to view Portal Stats/Usage Overview

### ISSUE THREAD

**Issue by Cayley** [service-portal/documentation#93]
I'm trying to find what roles or ACLs grant permissions for users to view the Service Portal > Usage Overview graphs page

This is something we are interested in giving read access to for a group of non admins for analytic purposes

Thanks
Cayley

**Comment by enojardi** [comment]
Hi Cayley, I believe the role you're looking for is 'sp_admin' since the usage overview are just reports from this table :) Unfortunately, this role also gives them SP admin to everything else (create pages, etc etc)

**Comment by Cayley** [comment]
Cheers, shame this isn't separated out - no worries though :)
