### ISSUE TITLE
SP Best Practices

### ISSUE THREAD

**Issue by enojardi** [service-portal/documentation#94]
Are there any plans in creating a documentation section for SP / Widget best practices?

Initially it would be nice to have some stuff targeted to low-code to pro-code developer audience:
- Angular vs DOM manipulation vs JQuery usage
- HTML / Angular directives
- CSS/SCSS

Eventually, things for no-code personas too: Portal setup, pages, theme management etc.

Cheers
Jonny

**Comment by omidborjianNow** [comment]
Absolutely, as far as the widget development is concerned.
For the low-code/no-code experience, we will be leveraging the ServiceNow documentation site. We'd like to keep the github documentation tailored towards the pro-code audience.

Cheers,
Omid
