### ISSUE TITLE
Scripted List Menu Type Issue

### ISSUE THREAD

**Issue by infotechconsulting** [service-portal/documentation#95]
@patrickw14 Do we have any documentation on where to edit the Scripted List menu type. I have a customer who would always like to show the Approvals and Request scripted menu items, but the code that suggests `ng-if="item.scriptedItems.count > 0"` is hidden somewhere in serviceNow and at first pass I won't be able to alter it. Please advise.

**Comment by pwydra23** [comment]
You are probably all set with this, since it has been 2 months, but updating this for other users.

This logic is in the Angular Template 'menuTemplate', which is related to the Header Menu widget. You can remove it in there.

**Comment by patrickw14** [comment]
^ Thank you for the response!
