### ISSUE TITLE
Widget CSS not applied to uibModal

### ISSUE THREAD

**Issue by nick-pike** [service-portal/documentation#96]
I've got a widget that triggers a uibModal (template coming from an ng-template), and I have some CSS in the widget, however it doesn't appear to be applying to the modal content.

It appears as though the modal gets created outside the div that has the widget sys_id class, causing the widget css not not be applied.

Is this expected behaviour?

**Comment by patrickw14** [comment]
Modals are created at the top-level - this is just how Bootstrap does modals. Best bet for applying CSS inside it is to either define your CSS at the page or theme level, or to embed a widget inside the modal and define your omdal CSS there.
