### ISSUE TITLE
Document Search API

### ISSUE THREAD

**Issue by dynamicdan** [service-portal/documentation#97]
It seems that there is no server side API BUT there is a widget that does some fancy stuff ("Search Page").

2 issues for search:
 1. Is there an API (client or server) we can document?
 1. Please document abilities of search including direct access via URL: `/sp?id=search&t=kb&q=mac&search=` (I've worked out t = type like "kb" or "sc" and q = query)

**Comment by patrickw14** [comment]
Unfortunately, the current search functionality isn't particularly extensible - in Helsinki, the best thing to do is to just clone the widget if you want to add new search parameters. There isn't really much there to document.
However, search in SP is going through a pretty big change in Istanbul that should make extending search, adding and removing new search types, and changing the templates MUCH easier. Once I ships, we will have docs on that! Stay tuned.
