### ISSUE TITLE
Pass data between widgets

### ISSUE THREAD

**Issue by chhinendu** [service-portal/documentation#98]
Can anyone help me understand if we can pass data between widgets ? 
Ex. Widget1 is embedded into Widget2. We can pass data from Widget2 to Widget1 while it(widget1) is initialised from Widget2. But can we transfer data back from widget1 to widget2 ?

**Comment by zzjasonzz** [comment]
The easiest way we've found is to use $broadcast from the sending widget and $scope.$on on the receiving widget to receive the message/data being broadcast.

**Comment by chhinendu** [comment]
cool. thanks @zzjasonzz will try it out

**Comment by zzjasonzz** [comment]
$rootScope.$broadcast('sp.message', data)

$scope.$on('sp.message', function(data))

Something like that

**Comment by chhinendu** [comment]
@zzjasonzz Quick question, will $broadcast work if I have 2 different widgets in my page and want to share data between these widgets?

**Comment by patrickw14** [comment]
^ Yep, as long as you're calling it from $rootScope. It works exactly the same way as above

**Comment by chhinendu** [comment]
thanks @patrickw14

**Comment by abhijitvbhosale** [comment]
https://community.servicenow.com/community/develop/blog/2016/06/26/how-to-communicate-between-two-widgets-in-service-portal
