### ISSUE TITLE
Update Live Chat link functionality

### ISSUE THREAD

**Issue by SonuDubey21** [service-portal/documentation#99]
I have a requirement to update the Live Chat functionality. Currently, when I click on Live Chat, it opens the configured queue for the portal. My requirement is to open new page once I click Live Chat and have links for all configured Queue (HR, Finance etc.)? Any idea how can I change this OOB behavior?

**Comment by patrickw14** [comment]
You can consider creating your own widget, separate from the existing Live Chat link, which grabs a list of your chat queues in your instance and renders links to those in the same way that the Live Chat link does today. Will require a small amount of custom code, but nothing too complicated.
